In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
path = (r"C:\Users\HP\Desktop\AI_project\week-05-visualization-first-models-and-ML\datasets\students.csv")

In [70]:
df = pd.read_csv(path,usecols=['study_hours' ,"final_marks" ])

In [71]:
df.head()

   study_hours  final_marks
0          8.1         68.5
1          5.2         54.4
2          4.0         68.7
3          2.5         56.8
4          7.7         68.8

In [72]:
df.shape

(184, 2)

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  179 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB

In [74]:
df.describe()

       study_hours  final_marks
count   179.000000   184.000000
mean      7.256983    65.119565
std       4.888808    11.508669
min       0.500000    32.100000
25%       3.650000    58.175000
50%       6.400000    65.700000
75%       8.850000    72.725000
max      30.000000    92.400000

In [75]:
df['study_hours']

0      8.1
1      5.2
2      4.0
3      2.5
4      7.7
      ...
179    5.5
180    3.5
181    1.4
182    7.9
183    6.3
Name: study_hours, Length: 184, dtype: float64

In [76]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  184 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB

In [78]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].median())

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  184 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB

In [80]:
df.shape

(184, 2)

In [81]:
x_train = df['study_hours'].iloc[0:147]
y_train = df['final_marks'].iloc[0:147]

In [82]:
x_test = df['study_hours'].iloc[147:]
y_test = df['final_marks'].iloc[147:]

In [83]:
x_train

0       8.1
1       5.2
2       4.0
3       2.5
4       7.7
       ...
142    17.2
143    18.9
144     6.2
145     3.5
146    19.9
Name: study_hours, Length: 147, dtype: float64

In [84]:
y_train

0      68.5
1      54.4
2      68.7
3      56.8
4      68.8
       ...
142    78.0
143    79.1
144    52.3
145    62.3
146    88.4
Name: final_marks, Length: 147, dtype: float64

In [85]:
x_train= np.array(x_train)
y_train= np.array(y_train)
x_test= np.array(x_test)
y_test= np.array(y_test)

In [86]:
class LinearRegression:
    count = 0
    def __init__(self, m=0, b=0, alpha=0):
        self.alpha = alpha
        self.m = m
        self.b = b
        self.history = []

    def predict(self, x) :
        return self.m * x + self.b

    def cost(self, x, y):
        y_hat = self.predict(x)
        error = y_hat - y
        loss = (1/(2*len(x)) )* np.sum(error**2)
        return loss

    def gradeint(self,x ,y):
        y_hat = self.predict(x)
        error = y_hat - y
        gm = np.sum (error* x) /len(x)
        gb = np.sum(error) /len(x)
        return gm,gb

    def run_epoch(self,x,y):
        gm, gb = self.gradeint(x,y)
        self.m -= self.alpha * gm
        self.b -= self.alpha * gb
        loss = self.cost(x,y)
        self.history.append((self.m, self.b, loss))
        self.count += 1
        print(f"Epoch : {self.count} -- m : {self.m} -- b : {self.b} -- cost : {loss}")


    def fit(self,epoch ,x,y):
        for i in range( 1,epoch+1):
            self.run_epoch(x,y)

In [87]:
model = LinearRegression(1,1,0.01)
model.fit(700, x_train,y_train)

Epoch : 1 -- m : 5.232264870541083 -- b : 1.5682935431155702 -- cost : 535.0446231973267
Epoch : 2 -- m : 6.18906570358156 -- b : 1.8236518221462896 -- cost : 473.7624720826851
Epoch : 3 -- m : 6.396161179056569 -- b : 2.0069950614595276 -- cost : 468.04332702241436
Epoch : 4 -- m : 6.431688391578847 -- b : 2.173470231125182 -- cost : 465.2507313131026
Epoch : 5 -- m : 6.427980759853007 -- b : 2.3357014582561906 -- cost : 462.62677757986813
Epoch : 6 -- m : 6.415328821958863 -- b : 2.4965795383303546 -- cost : 460.0268751444302
Epoch : 7 -- m : 6.400665862704679 -- b : 2.656767338099107 -- cost : 457.4433549416931
Epoch : 8 -- m : 6.385578774774345 -- b : 2.8164177557166297 -- cost : 454.87572229485187
Epoch : 9 -- m : 6.370430680991576 -- b : 2.975566955734076 -- cost : 452.32385898934876
Epoch : 10 -- m : 6.355304587939787 -- b : 3.1342243792067337 -- cost : 449.7876671016402
Epoch : 11 -- m : 6.340219384929229 -- b : 3.2923933466994897 -- cost : 447.26705033462855
Epoch : 12 -- m : 6.3251792853937685 -- b : 3.4500757742527397 -- cost : 444.76191303629747
Epoch : 13 -- m : 6.310185143850283 -- b : 3.6072732528612335 -- cost : 442.27216014485754
Epoch : 14 -- m : 6.29523704630951 -- b : 3.7639872955738864 -- cost : 439.7976971824549
Epoch : 15 -- m : 6.280334903210858 -- b : 3.9202193940649512 -- cost : 437.3384302514454
Epoch : 16 -- m : 6.265478585142056 -- b : 4.075971031593824 -- cost : 434.8942660308241
Epoch : 17 -- m : 6.250667953903859 -- b : 4.231243685982326 -- cost : 432.4651117726839
Epoch : 18 -- m : 6.235902869619626 -- b : 4.386038830306999 -- cost : 430.05087529869587
Epoch : 19 -- m : 6.221183192361645 -- b : 4.540357933068329 -- cost : 427.65146499661114
Epoch : 20 -- m : 6.206508782522369 -- b : 4.694202458240213 -- cost : 425.266789816785
Epoch : 21 -- m : 6.191879500898376 -- b : 4.847573865291985 -- cost : 422.8967592687217
Epoch : 22 -- m : 6.177295208708563 -- b : 5.000473609204123 -- cost : 420.54128341764044
Epoch : 23 -- m : 6.1627557675973 -- b : 5.152903140482476 -- cost : 418.2002728810628
Epoch : 24 -- m : 6.148261039634141 -- b : 5.304863905172122 -- cost : 415.87363882542104
Epoch : 25 -- m : 6.1338108873127455 -- b : 5.456357344871112 -- cost : 413.56129296268676
Epoch : 26 -- m : 6.119405173549633 -- b : 5.607384896744145 -- cost : 411.2631475470218
Epoch : 27 -- m : 6.10504376168289 -- b : 5.75794799353621 -- cost : 408.9791153714468
Epoch : 28 -- m : 6.090726515470883 -- b : 5.9080480635861745 -- cost : 406.7091097645335
Epoch : 29 -- m : 6.076453299090956 -- b : 6.057686530840332 -- cost : 404.4530445871151
Epoch : 30 -- m : 6.062223977138154 -- b : 6.2068648148659165 -- cost : 402.2108342290179
Epoch : 31 -- m : 6.04803841462393 -- b : 6.3555843308645645 -- cost : 399.9823936058123
Epoch : 32 -- m : 6.033896476974866 -- b : 6.503846489685744 -- cost : 397.7676381555848
Epoch : 33 -- m : 6.019798030031402 -- b : 6.651652697840135 -- cost : 395.5664838357281
Epoch : 34 -- m : 6.005742940046555 -- b : 6.799004357512978 -- cost : 393.3788471197531
Epoch : 35 -- m : 5.991731073684656 -- b : 6.94590286657737 -- cost : 391.20464499411867
Epoch : 36 -- m : 5.9777622980200835 -- b : 7.092349618607529 -- cost : 389.0437949550816
Epoch : 37 -- m : 5.963836480536 -- b : 7.238346002892015 -- cost : 386.89621500556615
Epoch : 38 -- m : 5.9499534891231 -- b : 7.383893404446906 -- cost : 384.76182365205227
Epoch : 39 -- m : 5.936113192078352 -- b : 7.528993204028941 -- cost : 382.6405399014835
Epoch : 40 -- m : 5.922315458103751 -- b : 7.673646778148619 -- cost : 380.53228325819293
Epoch : 41 -- m : 5.908560156305073 -- b : 7.817855499083253 -- cost : 378.4369737208494
Epoch : 42 -- m : 5.894847156190635 -- b : 7.961620734889992 -- cost : 376.3545317794212
Epoch : 43 -- m : 5.88117632767005 -- b : 8.1049438494188 -- cost : 374.28487841215923
Epoch : 44 -- m : 5.867547541053004 -- b : 8.247826202325392 -- cost : 372.22793508259826
Epoch : 45 -- m : 5.853960667048016 -- b : 8.39026914908413 -- cost : 370.18362373657664
Epoch : 46 -- m : 5.840415576761216 -- b : 8.532274041000889 -- cost : 368.15186679927456
Epoch : 47 -- m : 5.826912141695121 -- b : 8.673842225225872 -- cost : 366.13258717227035
Epoch : 48 -- m : 5.813450233747417 -- b : 8.81497504476639 -- cost : 364.1257082306147
Epoch : 49 -- m : 5.800029725209744 -- b : 8.955673838499603 -- cost : 362.1311538199232
Epoch : 50 -- m : 5.786650488766481 -- b : 9.095939941185224 -- cost : 360.14884825348616
Epoch : 51 -- m : 5.773312397493543 -- b : 9.235774683478173 -- cost : 358.17871630939715
Epoch : 52 -- m : 5.760015324857173 -- b : 9.375179391941213 -- cost : 356.22068322769803
Epoch : 53 -- m : 5.746759144712746 -- b : 9.514155389057525 -- cost : 354.2746747075422
Epoch : 54 -- m : 5.733543731303566 -- b : 9.652703993243257 -- cost : 352.34061690437545
Epoch : 55 -- m : 5.720368959259679 -- b : 9.790826518860033 -- cost : 350.41843642713354
Epoch : 56 -- m : 5.707234703596681 -- b : 9.928524276227419 -- cost : 348.50806033545683
Epoch : 57 -- m : 5.694140839714532 -- b : 10.065798571635353 -- cost : 346.60941613692336
Epoch : 58 -- m : 5.681087243396374 -- b : 10.202650707356543 -- cost : 344.7224317842973
Epoch : 59 -- m : 5.668073790807355 -- b : 10.339081981658815 -- cost : 342.84703567279536
Epoch : 60 -- m : 5.655100358493452 -- b : 10.47509368881743 -- cost : 340.9831566373693
Epoch : 61 -- m : 5.642166823380298 -- b : 10.61068711912737 -- cost : 339.13072395000563
Epoch : 62 -- m : 5.629273062772018 -- b : 10.745863558915564 -- cost : 337.28966731704185
Epoch : 63 -- m : 5.616418954350065 -- b : 10.880624290553104 -- cost : 335.4599168764988
Epoch : 64 -- m : 5.603604376172057 -- b : 11.014970592467407 -- cost : 333.6414031954299
Epoch : 65 -- m : 5.59082920667062 -- b : 11.148903739154338 -- cost : 331.83405726728614
Epoch : 66 -- m : 5.57809332465224 -- b : 11.282425001190308 -- cost : 330.03781050929746
Epoch : 67 -- m : 5.565396609296105 -- b : 11.415535645244322 -- cost : 328.2525947598706
Epoch : 68 -- m : 5.552738940152967 -- b : 11.548236934089998 -- cost : 326.4783422760023
Epoch : 69 -- m : 5.5401201971439935 -- b : 11.680530126617544 -- cost : 324.714985730709
Epoch : 70 -- m : 5.527540260559631 -- b : 11.812416477845707 -- cost : 322.9624582104713
Epoch : 71 -- m : 5.514999011058468 -- b : 11.943897238933669 -- cost : 321.2206932126961
Epoch : 72 -- m : 5.502496329666107 -- b : 12.074973657192926 -- cost : 319.48962464319135
Epoch : 73 -- m : 5.490032097774027 -- b : 12.205646976099114 -- cost : 317.7691868136595
Epoch : 74 -- m : 5.47760619713847 -- b : 12.335918435303808 -- cost : 316.05931443920406
Epoch : 75 -- m : 5.465218509879307 -- b : 12.465789270646285 -- cost : 314.3599426358524
Epoch : 76 -- m : 5.45286891847893 -- b : 12.59526071416524 -- cost : 312.6710069180937
Epoch : 77 -- m : 5.440557305781132 -- b : 12.724333994110484 -- cost : 310.992443196432
Epoch : 78 -- m : 5.428283554989997 -- b : 12.85301033495459 -- cost : 309.3241877749539
Epoch : 79 -- m : 5.4160475496687885 -- b : 12.981290957404505 -- cost : 307.6661773489119
Epoch : 80 -- m : 5.403849173738852 -- b : 13.109177078413143 -- cost : 306.0183490023219
Epoch : 81 -- m : 5.391688311478507 -- b : 13.23666991119092 -- cost : 304.38064020557584
Epoch : 82 -- m : 5.379564847521953 -- b : 13.36377066521726 -- cost : 302.75298881306924
Epoch : 83 -- m : 5.367478666858174 -- b : 13.490480546252082 -- cost : 301.1353330608422
Epoch : 84 -- m : 5.355429654829847 -- b : 13.616800756347226 -- cost : 299.52761156423657
Epoch : 85 -- m : 5.343417697132255 -- b : 13.742732493857865 -- cost : 297.92976331556594
Epoch : 86 -- m : 5.331442679812202 -- b : 13.868276953453869 -- cost : 296.3417276818009
Epoch : 87 -- m : 5.319504489266933 -- b : 13.993435326131136 -- cost : 294.7634444022682
Epoch : 88 -- m : 5.307603012243056 -- b : 14.1182087992229 -- cost : 293.19485358636393
Epoch : 89 -- m : 5.295738135835464 -- b : 14.242598556410984 -- cost : 291.635895711281
Epoch : 90 -- m : 5.283909747486271 -- b : 14.366605777737036 -- cost : 290.0865116197504
Epoch : 91 -- m : 5.2721177349837385 -- b : 14.49023163961372 -- cost : 288.5466425177964
Epoch : 92 -- m : 5.260361986461214 -- b : 14.61347731483588 -- cost : 287.01622997250536
Epoch : 93 -- m : 5.248642390396065 -- b : 14.73634397259166 -- cost : 285.49521590980885
Epoch : 94 -- m : 5.23695883560863 -- b : 14.858832778473603 -- cost : 283.9835426122792
Epoch : 95 -- m : 5.225311211261154 -- b : 14.980944894489705 -- cost : 282.48115271694013
Epoch : 96 -- m : 5.213699406856744 -- b : 15.102681479074434 -- cost : 280.9879892130891
Epoch : 97 -- m : 5.2021233122383155 -- b : 15.224043687099728 -- cost : 279.50399544013516
Epoch : 98 -- m : 5.190582817587553 -- b : 15.345032669885947 -- cost : 278.02911508544753
Epoch : 99 -- m : 5.179077813423864 -- b : 15.465649575212794 -- cost : 276.56329218221964
Epoch : 100 -- m : 5.167608190603341 -- b : 15.585895547330203 -- cost : 275.10647110734504
Epoch : 101 -- m : 5.156173840317727 -- b : 15.705771726969198 -- cost : 273.65859657930685
Epoch : 102 -- m : 5.144774654093386 -- b : 15.825279251352713 -- cost : 272.2196136560797
Epoch : 103 -- m : 5.133410523790266 -- b : 15.944419254206377 -- cost : 270.7894677330452
Epoch : 104 -- m : 5.1220813416008815 -- b : 16.063192865769274 -- cost : 269.36810454091983
Epoch : 105 -- m : 5.110787000049287 -- b : 16.181601212804665 -- cost : 267.9554701436953
Epoch : 106 -- m : 5.0995273919900574 -- b : 16.299645418610677 -- cost : 266.5515109365921
Epoch : 107 -- m : 5.0883024106072705 -- b : 16.41732660303095 -- cost : 265.1561736440255
Epoch : 108 -- m : 5.077111949413498 -- b : 16.534645882465277 -- cost : 263.7694053175837
Epoch : 109 -- m : 5.065955902248792 -- b : 16.65160436988018 -- cost : 262.39115333401855
Epoch : 110 -- m : 5.054834163279676 -- b : 16.768203174819476 -- cost : 261.02136539324914
Epoch : 111 -- m : 5.043746626998144 -- b : 16.884443403414807 -- cost : 259.6599895163764
Epoch : 112 -- m : 5.0326931882206605 -- b : 17.000326158396124 -- cost : 258.3069740437113
Epoch : 113 -- m : 5.0216737420871596 -- b : 17.11585253910215 -- cost : 256.96226763281464
Epoch : 114 -- m : 5.010688184060052 -- b : 17.231023641490815 -- cost : 255.62581925654806
Epoch : 115 -- m : 4.999736409923231 -- b : 17.345840558149643 -- cost : 254.2975782011384
Epoch : 116 -- m : 4.98881831578109 -- b : 17.460304378306134 -- cost : 252.97749406425305
Epoch : 117 -- m : 4.97793379805753 -- b : 17.574416187838075 -- cost : 251.66551675308725
Epoch : 118 -- m : 4.967082753494977 -- b : 17.688177069283864 -- cost : 250.36159648246328
Epoch : 119 -- m : 4.95626507915341 -- b : 17.801588101852754 -- cost : 249.06568377294158
Epoch : 120 -- m : 4.945480672409377 -- b : 17.914650361435122 -- cost : 247.7777294489426
Epoch : 121 -- m : 4.934729430955024 -- b : 18.027364920612644 -- cost : 246.49768463688127
Epoch : 122 -- m : 4.924011252797124 -- b : 18.139732848668494 -- cost : 245.22550076331217
Epoch : 123 -- m : 4.913326036256111 -- b : 18.25175521159748 -- cost : 243.96112955308624
Epoch : 124 -- m : 4.902673679965112 -- b : 18.36343307211615 -- cost : 242.70452302751923
Epoch : 125 -- m : 4.892054082868991 -- b : 18.474767489672878 -- cost : 241.45563350257078
Epoch : 126 -- m : 4.881467144223384 -- b : 18.585759520457927 -- cost : 240.21441358703493
Epoch : 127 -- m : 4.870912763593747 -- b : 18.696410217413447 -- cost : 238.98081618074195
Epoch : 128 -- m : 4.860390840854404 -- b : 18.80672063024348 -- cost : 237.75479447277118
Epoch : 129 -- m : 4.849901276187592 -- b : 18.91669180542391 -- cost : 236.53630193967436
Epoch : 130 -- m : 4.839443970082521 -- b : 19.026324786212395 -- cost : 235.32529234371032
Epoch : 131 -- m : 4.829018823334424 -- b : 19.135620612658265 -- cost : 234.12171973109065
Epoch : 132 -- m : 4.818625737043622 -- b : 19.24458032161238 -- cost : 232.92553843023566
Epoch : 133 -- m : 4.808264612614578 -- b : 19.353204946736973 -- cost : 231.7367030500414
Epoch : 134 -- m : 4.797935351754969 -- b : 19.461495518515463 -- cost : 230.55516847815707
Epoch : 135 -- m : 4.787637856474748 -- b : 19.569453064262213 -- cost : 229.3808898792735
Epoch : 136 -- m : 4.777372029085219 -- b : 19.67707860813229 -- cost : 228.21382269342138
Epoch : 137 -- m : 4.767137772198106 -- b : 19.784373171131183 -- cost : 227.05392263428055
Epoch : 138 -- m : 4.756934988724634 -- b : 19.89133777112447 -- cost : 225.90114568749962
Epoch : 139 -- m : 4.746763581874602 -- b : 19.997973422847494 -- cost : 224.75544810902556
Epoch : 140 -- m : 4.7366234551554705 -- b : 20.10428113791498 -- cost : 223.61678642344387
Epoch : 141 -- m : 4.726514512371442 -- b : 20.21026192483064 -- cost : 222.4851174223287
Epoch : 142 -- m : 4.71643665762255 -- b : 20.315916788996724 -- cost : 221.36039816260336
Epoch : 143 -- m : 4.70638979530375 -- b : 20.421246732723574 -- cost : 220.24258596491092
Epoch : 144 -- m : 4.696373830104011 -- b : 20.526252755239128 -- cost : 219.1316384119942
Epoch : 145 -- m : 4.686388667005413 -- b : 20.630935852698393 -- cost : 218.02751334708674
Epoch : 146 -- m : 4.676434211282243 -- b : 20.735297018192902 -- cost : 216.93016887231272
Epoch : 147 -- m : 4.6665103685001 -- b : 20.839337241760138 -- cost : 215.839563347097
Epoch : 148 -- m : 4.656617044514996 -- b : 20.943057510392915 -- cost : 214.75565538658543
Epoch : 149 -- m : 4.646754145472465 -- b : 21.04645880804875 -- cost : 213.6784038600741
Epoch : 150 -- m : 4.636921577806669 -- b : 21.1495421156592 -- cost : 212.6077678894485
Epoch : 151 -- m : 4.6271192482395165 -- b : 21.252308411139158 -- cost : 211.5437068476327
Epoch : 152 -- m : 4.617347063779771 -- b : 21.35475866939613 -- cost : 210.4861803570474
Epoch : 153 -- m : 4.607604931722176 -- b : 21.456893862339495 -- cost : 209.43514828807764
Epoch : 154 -- m : 4.597892759646567 -- b : 21.55871495888972 -- cost : 208.39057075755034
Epoch : 155 -- m : 4.588210455417002 -- b : 21.660222924987547 -- cost : 207.3524081272206
Epoch : 156 -- m : 4.578557927180884 -- b : 21.761418723603164 -- cost : 206.32062100226773
Epoch : 157 -- m : 4.568935083368091 -- b : 21.86230331474533 -- cost : 205.29517022980025
Epoch : 158 -- m : 4.559341832690105 -- b : 21.962877655470493 -- cost : 204.27601689737014
Epoch : 159 -- m : 4.54977808413915 -- b : 22.063142699891866 -- cost : 203.26312233149645
Epoch : 160 -- m : 4.540243746987323 -- b : 22.16309939918848 -- cost : 202.25644809619735
Epoch : 161 -- m : 4.530738730785739 -- b : 22.262748701614193 -- cost : 201.25595599153215
Epoch : 162 -- m : 4.52126294536367 -- b : 22.36209155250671 -- cost : 200.26160805215133
Epoch : 163 -- m : 4.51181630082769 -- b : 22.46112889429653 -- cost : 199.27336654585602
Epoch : 164 -- m : 4.502398707560824 -- b : 22.5598616665159 -- cost : 198.29119397216624
Epoch : 165 -- m : 4.493010076221691 -- b : 22.658290805807727 -- cost : 197.31505306089772
Epoch : 166 -- m : 4.483650317743667 -- b : 22.75641724593445 -- cost : 196.3449067707479
Epoch : 167 -- m : 4.474319343334032 -- b : 22.854241917786915 -- cost : 195.38071828789006
Epoch : 168 -- m : 4.465017064473131 -- b : 22.951765749393196 -- cost : 194.42245102457636
Epoch : 169 -- m : 4.455743392913534 -- b : 23.048989665927405 -- cost : 193.47006861774977
Epoch : 170 -- m : 4.446498240679196 -- b : 23.145914589718462 -- cost : 192.52353492766377
Epoch : 171 -- m : 4.437281520064627 -- b : 23.242541440258854 -- cost : 191.58281403651148
Epoch : 172 -- m : 4.428093143634059 -- b : 23.338871134213345 -- cost : 190.64787024706214
Epoch : 173 -- m : 4.418933024220611 -- b : 23.434904585427685 -- cost : 189.71866808130704
Epoch : 174 -- m : 4.40980107492547 -- b : 23.53064270493727 -- cost : 188.7951722791127
Epoch : 175 -- m : 4.4006972091170615 -- b : 23.626086400975794 -- cost : 187.87734779688356
Epoch : 176 -- m : 4.39162134043023 -- b : 23.721236578983852 -- cost : 186.96515980623144
Epoch : 177 -- m : 4.382573382765417 -- b : 23.816094141617548 -- cost : 186.05857369265442
Epoch : 178 -- m : 4.373553250287848 -- b : 23.910659988757036 -- cost : 185.15755505422325
Epoch : 179 -- m : 4.364560857426714 -- b : 24.004935017515074 -- cost : 184.26206970027584
Epoch : 180 -- m : 4.355596118874364 -- b : 24.098920122245527 -- cost : 183.37208365011978
Epoch : 181 -- m : 4.3466589495854935 -- b : 24.192616194551857 -- cost : 182.48756313174295
Epoch : 182 -- m : 4.337749264776337 -- b : 24.286024123295572 -- cost : 181.60847458053206
Epoch : 183 -- m : 4.328866979923865 -- b : 24.37914479460467 -- cost : 180.7347846379989
Epoch : 184 -- m : 4.320012010764981 -- b : 24.471979091882037 -- cost : 179.86646015051443
Epoch : 185 -- m : 4.311184273295724 -- b : 24.564527895813825 -- cost : 179.003468168051
Epoch : 186 -- m : 4.3023836837704685 -- b : 24.656792084377816 -- cost : 178.14577594293164
Epoch : 187 -- m : 4.293610158701134 -- b : 24.74877253285175 -- cost : 177.29335092858742
Epoch : 188 -- m : 4.28486361485639 -- b : 24.840470113821617 -- cost : 176.4461607783229
Epoch : 189 -- m : 4.276143969260868 -- b : 24.931885697189948 -- cost : 175.60417334408805
Epoch : 190 -- m : 4.267451139194373 -- b : 25.023020150184063 -- cost : 174.76735667525872
Epoch : 191 -- m : 4.258785042191099 -- b : 25.113874337364297 -- cost : 173.93567901742412
Epoch : 192 -- m : 4.2501455960388475 -- b : 25.2044491206322 -- cost : 173.1091088111818
Epoch : 193 -- m : 4.241532718778248 -- b : 25.294745359238718 -- cost : 172.2876146909402
Epoch : 194 -- m : 4.2329463287019795 -- b : 25.38476390979234 -- cost : 171.4711654837282
Epoch : 195 -- m : 4.224386344353994 -- b : 25.47450562626723 -- cost : 170.6597302080126
Epoch : 196 -- m : 4.215852684528747 -- b : 25.563971360011323 -- cost : 169.85327807252193
Epoch : 197 -- m : 4.2073452682704255 -- b : 25.653161959754403 -- cost : 169.05177847507866
Epoch : 198 -- m : 4.1988640148721785 -- b : 25.742078271616155 -- cost : 168.2552010014373
Epoch : 199 -- m : 4.190408843875353 -- b : 25.830721139114193 -- cost : 167.46351542413083
Epoch : 200 -- m : 4.1819796750687335 -- b : 25.91909140317206 -- cost : 166.67669170132328
Epoch : 201 -- m : 4.173576428487774 -- b : 26.007189902127212 -- cost : 165.89469997567
Epoch : 202 -- m : 4.165199024413845 -- b : 26.095017471738956 -- cost : 165.1175105731845
Epoch : 203 -- m : 4.156847383373476 -- b : 26.182574945196393 -- cost : 164.34509400211246
Epoch : 204 -- m : 4.148521426137602 -- b : 26.269863153126316 -- cost : 163.57742095181283
Epoch : 205 -- m : 4.140221073720811 -- b : 26.356882923601095 -- cost : 162.81446229164524
Epoch : 206 -- m : 4.131946247380593 -- b : 26.443635082146525 -- cost : 162.0561890698647
Epoch : 207 -- m : 4.123696868616596 -- b : 26.53012045174966 -- cost : 161.30257251252323
Epoch : 208 -- m : 4.1154728591698815 -- b : 26.616339852866624 -- cost : 160.55358402237772
Epoch : 209 -- m : 4.107274141022178 -- b : 26.702294103430393 -- cost : 159.80919517780464
Epoch : 210 -- m : 4.099100636395147 -- b : 26.787984018858555 -- cost : 159.06937773172194
Epoch : 211 -- m : 4.090952267749639 -- b : 26.873410412061038 -- cost : 158.3341036105169
Epoch : 212 -- m : 4.082828957784961 -- b : 26.95857409344783 -- cost : 157.6033449129808
Epoch : 213 -- m : 4.074730629438144 -- b : 27.043475870936668 -- cost : 156.87707390925027
Epoch : 214 -- m : 4.066657205883211 -- b : 27.128116549960698 -- cost : 156.15526303975506
Epoch : 215 -- m : 4.058608610530445 -- b : 27.212496933476114 -- cost : 155.43788491417212
Epoch : 216 -- m : 4.05058476702567 -- b : 27.296617821969782 -- cost : 154.72491231038634
Epoch : 217 -- m : 4.042585599249518 -- b : 27.380480013466833 -- cost : 154.01631817345748
Epoch : 218 -- m : 4.034611031316714 -- b : 27.464084303538222 -- cost : 153.31207561459357
Epoch : 219 -- m : 4.026660987575349 -- b : 27.547431485308294 -- cost : 152.61215791013058
Epoch : 220 -- m : 4.018735392606171 -- b : 27.630522349462293 -- cost : 151.91653850051827

In [88]:
m = 1
b = 1
alpha = 0.01

model = LinearRegression(m,b,alpha)

In [89]:
model.b

1

In [90]:
model.m

1

In [91]:
model.alpha

0.01

In [92]:
model.run_epoch(x_train , y_train)

Epoch : 1 -- m : 5.232264870541083 -- b : 1.5682935431155702 -- cost : 535.0446231973267

In [ ]:
for i in range(8,500):

    model.run_epoch(x_train , y_train)

Epoch : 2 -- m : 6.18906570358156 -- b : 1.8236518221462896 -- cost : 473.7624720826851
Epoch : 3 -- m : 6.396161179056569 -- b : 2.0069950614595276 -- cost : 468.04332702241436
Epoch : 4 -- m : 6.431688391578847 -- b : 2.173470231125182 -- cost : 465.2507313131026
Epoch : 5 -- m : 6.427980759853007 -- b : 2.3357014582561906 -- cost : 462.62677757986813
Epoch : 6 -- m : 6.415328821958863 -- b : 2.4965795383303546 -- cost : 460.0268751444302
Epoch : 7 -- m : 6.400665862704679 -- b : 2.656767338099107 -- cost : 457.4433549416931
Epoch : 8 -- m : 6.385578774774345 -- b : 2.8164177557166297 -- cost : 454.87572229485187
Epoch : 9 -- m : 6.370430680991576 -- b : 2.975566955734076 -- cost : 452.32385898934876
Epoch : 10 -- m : 6.355304587939787 -- b : 3.1342243792067337 -- cost : 449.7876671016402
Epoch : 11 -- m : 6.340219384929229 -- b : 3.2923933466994897 -- cost : 447.26705033462855
Epoch : 12 -- m : 6.3251792853937685 -- b : 3.4500757742527397 -- cost : 444.76191303629747
Epoch : 13 -- m : 6.310185143850283 -- b : 3.6072732528612335 -- cost : 442.27216014485754
Epoch : 14 -- m : 6.29523704630951 -- b : 3.7639872955738864 -- cost : 439.7976971824549
Epoch : 15 -- m : 6.280334903210858 -- b : 3.9202193940649512 -- cost : 437.3384302514454
Epoch : 16 -- m : 6.265478585142056 -- b : 4.075971031593824 -- cost : 434.8942660308241
Epoch : 17 -- m : 6.250667953903859 -- b : 4.231243685982326 -- cost : 432.4651117726839
Epoch : 18 -- m : 6.235902869619626 -- b : 4.386038830306999 -- cost : 430.05087529869587
Epoch : 19 -- m : 6.221183192361645 -- b : 4.540357933068329 -- cost : 427.65146499661114
Epoch : 20 -- m : 6.206508782522369 -- b : 4.694202458240213 -- cost : 425.266789816785
Epoch : 21 -- m : 6.191879500898376 -- b : 4.847573865291985 -- cost : 422.8967592687217
Epoch : 22 -- m : 6.177295208708563 -- b : 5.000473609204123 -- cost : 420.54128341764044
Epoch : 23 -- m : 6.1627557675973 -- b : 5.152903140482476 -- cost : 418.2002728810628
Epoch : 24 -- m : 6.148261039634141 -- b : 5.304863905172122 -- cost : 415.87363882542104
Epoch : 25 -- m : 6.1338108873127455 -- b : 5.456357344871112 -- cost : 413.56129296268676
Epoch : 26 -- m : 6.119405173549633 -- b : 5.607384896744145 -- cost : 411.2631475470218
Epoch : 27 -- m : 6.10504376168289 -- b : 5.75794799353621 -- cost : 408.9791153714468
Epoch : 28 -- m : 6.090726515470883 -- b : 5.9080480635861745 -- cost : 406.7091097645335
Epoch : 29 -- m : 6.076453299090956 -- b : 6.057686530840332 -- cost : 404.4530445871151
Epoch : 30 -- m : 6.062223977138154 -- b : 6.2068648148659165 -- cost : 402.2108342290179
Epoch : 31 -- m : 6.04803841462393 -- b : 6.3555843308645645 -- cost : 399.9823936058123
Epoch : 32 -- m : 6.033896476974866 -- b : 6.503846489685744 -- cost : 397.7676381555848
Epoch : 33 -- m : 6.019798030031402 -- b : 6.651652697840135 -- cost : 395.5664838357281
Epoch : 34 -- m : 6.005742940046555 -- b : 6.799004357512978 -- cost : 393.3788471197531
Epoch : 35 -- m : 5.991731073684656 -- b : 6.94590286657737 -- cost : 391.20464499411867
Epoch : 36 -- m : 5.9777622980200835 -- b : 7.092349618607529 -- cost : 389.0437949550816
Epoch : 37 -- m : 5.963836480536 -- b : 7.238346002892015 -- cost : 386.89621500556615
Epoch : 38 -- m : 5.9499534891231 -- b : 7.383893404446906 -- cost : 384.76182365205227
Epoch : 39 -- m : 5.936113192078352 -- b : 7.528993204028941 -- cost : 382.6405399014835
Epoch : 40 -- m : 5.922315458103751 -- b : 7.673646778148619 -- cost : 380.53228325819293
Epoch : 41 -- m : 5.908560156305073 -- b : 7.817855499083253 -- cost : 378.4369737208494
Epoch : 42 -- m : 5.894847156190635 -- b : 7.961620734889992 -- cost : 376.3545317794212
Epoch : 43 -- m : 5.88117632767005 -- b : 8.1049438494188 -- cost : 374.28487841215923
Epoch : 44 -- m : 5.867547541053004 -- b : 8.247826202325392 -- cost : 372.22793508259826
Epoch : 45 -- m : 5.853960667048016 -- b : 8.39026914908413 -- cost : 370.18362373657664
Epoch : 46 -- m : 5.840415576761216 -- b : 8.532274041000889 -- cost : 368.15186679927456
Epoch : 47 -- m : 5.826912141695121 -- b : 8.673842225225872 -- cost : 366.13258717227035
Epoch : 48 -- m : 5.813450233747417 -- b : 8.81497504476639 -- cost : 364.1257082306147
Epoch : 49 -- m : 5.800029725209744 -- b : 8.955673838499603 -- cost : 362.1311538199232
Epoch : 50 -- m : 5.786650488766481 -- b : 9.095939941185224 -- cost : 360.14884825348616
Epoch : 51 -- m : 5.773312397493543 -- b : 9.235774683478173 -- cost : 358.17871630939715
Epoch : 52 -- m : 5.760015324857173 -- b : 9.375179391941213 -- cost : 356.22068322769803
Epoch : 53 -- m : 5.746759144712746 -- b : 9.514155389057525 -- cost : 354.2746747075422
Epoch : 54 -- m : 5.733543731303566 -- b : 9.652703993243257 -- cost : 352.34061690437545
Epoch : 55 -- m : 5.720368959259679 -- b : 9.790826518860033 -- cost : 350.41843642713354
Epoch : 56 -- m : 5.707234703596681 -- b : 9.928524276227419 -- cost : 348.50806033545683
Epoch : 57 -- m : 5.694140839714532 -- b : 10.065798571635353 -- cost : 346.60941613692336
Epoch : 58 -- m : 5.681087243396374 -- b : 10.202650707356543 -- cost : 344.7224317842973
Epoch : 59 -- m : 5.668073790807355 -- b : 10.339081981658815 -- cost : 342.84703567279536
Epoch : 60 -- m : 5.655100358493452 -- b : 10.47509368881743 -- cost : 340.9831566373693
Epoch : 61 -- m : 5.642166823380298 -- b : 10.61068711912737 -- cost : 339.13072395000563
Epoch : 62 -- m : 5.629273062772018 -- b : 10.745863558915564 -- cost : 337.28966731704185
Epoch : 63 -- m : 5.616418954350065 -- b : 10.880624290553104 -- cost : 335.4599168764988
Epoch : 64 -- m : 5.603604376172057 -- b : 11.014970592467407 -- cost : 333.6414031954299
Epoch : 65 -- m : 5.59082920667062 -- b : 11.148903739154338 -- cost : 331.83405726728614
Epoch : 66 -- m : 5.57809332465224 -- b : 11.282425001190308 -- cost : 330.03781050929746
Epoch : 67 -- m : 5.565396609296105 -- b : 11.415535645244322 -- cost : 328.2525947598706
Epoch : 68 -- m : 5.552738940152967 -- b : 11.548236934089998 -- cost : 326.4783422760023
Epoch : 69 -- m : 5.5401201971439935 -- b : 11.680530126617544 -- cost : 324.714985730709
Epoch : 70 -- m : 5.527540260559631 -- b : 11.812416477845707 -- cost : 322.9624582104713
Epoch : 71 -- m : 5.514999011058468 -- b : 11.943897238933669 -- cost : 321.2206932126961
Epoch : 72 -- m : 5.502496329666107 -- b : 12.074973657192926 -- cost : 319.48962464319135
Epoch : 73 -- m : 5.490032097774027 -- b : 12.205646976099114 -- cost : 317.7691868136595
Epoch : 74 -- m : 5.47760619713847 -- b : 12.335918435303808 -- cost : 316.05931443920406
Epoch : 75 -- m : 5.465218509879307 -- b : 12.465789270646285 -- cost : 314.3599426358524
Epoch : 76 -- m : 5.45286891847893 -- b : 12.59526071416524 -- cost : 312.6710069180937
Epoch : 77 -- m : 5.440557305781132 -- b : 12.724333994110484 -- cost : 310.992443196432
Epoch : 78 -- m : 5.428283554989997 -- b : 12.85301033495459 -- cost : 309.3241877749539
Epoch : 79 -- m : 5.4160475496687885 -- b : 12.981290957404505 -- cost : 307.6661773489119
Epoch : 80 -- m : 5.403849173738852 -- b : 13.109177078413143 -- cost : 306.0183490023219
Epoch : 81 -- m : 5.391688311478507 -- b : 13.23666991119092 -- cost : 304.38064020557584
Epoch : 82 -- m : 5.379564847521953 -- b : 13.36377066521726 -- cost : 302.75298881306924
Epoch : 83 -- m : 5.367478666858174 -- b : 13.490480546252082 -- cost : 301.1353330608422
Epoch : 84 -- m : 5.355429654829847 -- b : 13.616800756347226 -- cost : 299.52761156423657
Epoch : 85 -- m : 5.343417697132255 -- b : 13.742732493857865 -- cost : 297.92976331556594
Epoch : 86 -- m : 5.331442679812202 -- b : 13.868276953453869 -- cost : 296.3417276818009
Epoch : 87 -- m : 5.319504489266933 -- b : 13.993435326131136 -- cost : 294.7634444022682
Epoch : 88 -- m : 5.307603012243056 -- b : 14.1182087992229 -- cost : 293.19485358636393
Epoch : 89 -- m : 5.295738135835464 -- b : 14.242598556410984 -- cost : 291.635895711281
Epoch : 90 -- m : 5.283909747486271 -- b : 14.366605777737036 -- cost : 290.0865116197504
Epoch : 91 -- m : 5.2721177349837385 -- b : 14.49023163961372 -- cost : 288.5466425177964
Epoch : 92 -- m : 5.260361986461214 -- b : 14.61347731483588 -- cost : 287.01622997250536
Epoch : 93 -- m : 5.248642390396065 -- b : 14.73634397259166 -- cost : 285.49521590980885
Epoch : 94 -- m : 5.23695883560863 -- b : 14.858832778473603 -- cost : 283.9835426122792
Epoch : 95 -- m : 5.225311211261154 -- b : 14.980944894489705 -- cost : 282.48115271694013
Epoch : 96 -- m : 5.213699406856744 -- b : 15.102681479074434 -- cost : 280.9879892130891
Epoch : 97 -- m : 5.2021233122383155 -- b : 15.224043687099728 -- cost : 279.50399544013516
Epoch : 98 -- m : 5.190582817587553 -- b : 15.345032669885947 -- cost : 278.02911508544753
Epoch : 99 -- m : 5.179077813423864 -- b : 15.465649575212794 -- cost : 276.56329218221964
Epoch : 100 -- m : 5.167608190603341 -- b : 15.585895547330203 -- cost : 275.10647110734504
Epoch : 101 -- m : 5.156173840317727 -- b : 15.705771726969198 -- cost : 273.65859657930685
Epoch : 102 -- m : 5.144774654093386 -- b : 15.825279251352713 -- cost : 272.2196136560797
Epoch : 103 -- m : 5.133410523790266 -- b : 15.944419254206377 -- cost : 270.7894677330452
Epoch : 104 -- m : 5.1220813416008815 -- b : 16.063192865769274 -- cost : 269.36810454091983
Epoch : 105 -- m : 5.110787000049287 -- b : 16.181601212804665 -- cost : 267.9554701436953
Epoch : 106 -- m : 5.0995273919900574 -- b : 16.299645418610677 -- cost : 266.5515109365921
Epoch : 107 -- m : 5.0883024106072705 -- b : 16.41732660303095 -- cost : 265.1561736440255
Epoch : 108 -- m : 5.077111949413498 -- b : 16.534645882465277 -- cost : 263.7694053175837
Epoch : 109 -- m : 5.065955902248792 -- b : 16.65160436988018 -- cost : 262.39115333401855
Epoch : 110 -- m : 5.054834163279676 -- b : 16.768203174819476 -- cost : 261.02136539324914
Epoch : 111 -- m : 5.043746626998144 -- b : 16.884443403414807 -- cost : 259.6599895163764
Epoch : 112 -- m : 5.0326931882206605 -- b : 17.000326158396124 -- cost : 258.3069740437113
Epoch : 113 -- m : 5.0216737420871596 -- b : 17.11585253910215 -- cost : 256.96226763281464
Epoch : 114 -- m : 5.010688184060052 -- b : 17.231023641490815 -- cost : 255.62581925654806
Epoch : 115 -- m : 4.999736409923231 -- b : 17.345840558149643 -- cost : 254.2975782011384
Epoch : 116 -- m : 4.98881831578109 -- b : 17.460304378306134 -- cost : 252.97749406425305
Epoch : 117 -- m : 4.97793379805753 -- b : 17.574416187838075 -- cost : 251.66551675308725
Epoch : 118 -- m : 4.967082753494977 -- b : 17.688177069283864 -- cost : 250.36159648246328
Epoch : 119 -- m : 4.95626507915341 -- b : 17.801588101852754 -- cost : 249.06568377294158
Epoch : 120 -- m : 4.945480672409377 -- b : 17.914650361435122 -- cost : 247.7777294489426
Epoch : 121 -- m : 4.934729430955024 -- b : 18.027364920612644 -- cost : 246.49768463688127
Epoch : 122 -- m : 4.924011252797124 -- b : 18.139732848668494 -- cost : 245.22550076331217
Epoch : 123 -- m : 4.913326036256111 -- b : 18.25175521159748 -- cost : 243.96112955308624
Epoch : 124 -- m : 4.902673679965112 -- b : 18.36343307211615 -- cost : 242.70452302751923
Epoch : 125 -- m : 4.892054082868991 -- b : 18.474767489672878 -- cost : 241.45563350257078
Epoch : 126 -- m : 4.881467144223384 -- b : 18.585759520457927 -- cost : 240.21441358703493
Epoch : 127 -- m : 4.870912763593747 -- b : 18.696410217413447 -- cost : 238.98081618074195
Epoch : 128 -- m : 4.860390840854404 -- b : 18.80672063024348 -- cost : 237.75479447277118
Epoch : 129 -- m : 4.849901276187592 -- b : 18.91669180542391 -- cost : 236.53630193967436
Epoch : 130 -- m : 4.839443970082521 -- b : 19.026324786212395 -- cost : 235.32529234371032
Epoch : 131 -- m : 4.829018823334424 -- b : 19.135620612658265 -- cost : 234.12171973109065
Epoch : 132 -- m : 4.818625737043622 -- b : 19.24458032161238 -- cost : 232.92553843023566
Epoch : 133 -- m : 4.808264612614578 -- b : 19.353204946736973 -- cost : 231.7367030500414
Epoch : 134 -- m : 4.797935351754969 -- b : 19.461495518515463 -- cost : 230.55516847815707
Epoch : 135 -- m : 4.787637856474748 -- b : 19.569453064262213 -- cost : 229.3808898792735
Epoch : 136 -- m : 4.777372029085219 -- b : 19.67707860813229 -- cost : 228.21382269342138
Epoch : 137 -- m : 4.767137772198106 -- b : 19.784373171131183 -- cost : 227.05392263428055
Epoch : 138 -- m : 4.756934988724634 -- b : 19.89133777112447 -- cost : 225.90114568749962
Epoch : 139 -- m : 4.746763581874602 -- b : 19.997973422847494 -- cost : 224.75544810902556
Epoch : 140 -- m : 4.7366234551554705 -- b : 20.10428113791498 -- cost : 223.61678642344387
Epoch : 141 -- m : 4.726514512371442 -- b : 20.21026192483064 -- cost : 222.4851174223287
Epoch : 142 -- m : 4.71643665762255 -- b : 20.315916788996724 -- cost : 221.36039816260336
Epoch : 143 -- m : 4.70638979530375 -- b : 20.421246732723574 -- cost : 220.24258596491092
Epoch : 144 -- m : 4.696373830104011 -- b : 20.526252755239128 -- cost : 219.1316384119942
Epoch : 145 -- m : 4.686388667005413 -- b : 20.630935852698393 -- cost : 218.02751334708674
Epoch : 146 -- m : 4.676434211282243 -- b : 20.735297018192902 -- cost : 216.93016887231272
Epoch : 147 -- m : 4.6665103685001 -- b : 20.839337241760138 -- cost : 215.839563347097
Epoch : 148 -- m : 4.656617044514996 -- b : 20.943057510392915 -- cost : 214.75565538658543
Epoch : 149 -- m : 4.646754145472465 -- b : 21.04645880804875 -- cost : 213.6784038600741
Epoch : 150 -- m : 4.636921577806669 -- b : 21.1495421156592 -- cost : 212.6077678894485
Epoch : 151 -- m : 4.6271192482395165 -- b : 21.252308411139158 -- cost : 211.5437068476327
Epoch : 152 -- m : 4.617347063779771 -- b : 21.35475866939613 -- cost : 210.4861803570474
Epoch : 153 -- m : 4.607604931722176 -- b : 21.456893862339495 -- cost : 209.43514828807764
Epoch : 154 -- m : 4.597892759646567 -- b : 21.55871495888972 -- cost : 208.39057075755034
Epoch : 155 -- m : 4.588210455417002 -- b : 21.660222924987547 -- cost : 207.3524081272206
Epoch : 156 -- m : 4.578557927180884 -- b : 21.761418723603164 -- cost : 206.32062100226773
Epoch : 157 -- m : 4.568935083368091 -- b : 21.86230331474533 -- cost : 205.29517022980025
Epoch : 158 -- m : 4.559341832690105 -- b : 21.962877655470493 -- cost : 204.27601689737014
Epoch : 159 -- m : 4.54977808413915 -- b : 22.063142699891866 -- cost : 203.26312233149645
Epoch : 160 -- m : 4.540243746987323 -- b : 22.16309939918848 -- cost : 202.25644809619735
Epoch : 161 -- m : 4.530738730785739 -- b : 22.262748701614193 -- cost : 201.25595599153215
Epoch : 162 -- m : 4.52126294536367 -- b : 22.36209155250671 -- cost : 200.26160805215133
Epoch : 163 -- m : 4.51181630082769 -- b : 22.46112889429653 -- cost : 199.27336654585602
Epoch : 164 -- m : 4.502398707560824 -- b : 22.5598616665159 -- cost : 198.29119397216624
Epoch : 165 -- m : 4.493010076221691 -- b : 22.658290805807727 -- cost : 197.31505306089772
Epoch : 166 -- m : 4.483650317743667 -- b : 22.75641724593445 -- cost : 196.3449067707479
Epoch : 167 -- m : 4.474319343334032 -- b : 22.854241917786915 -- cost : 195.38071828789006
Epoch : 168 -- m : 4.465017064473131 -- b : 22.951765749393196 -- cost : 194.42245102457636
Epoch : 169 -- m : 4.455743392913534 -- b : 23.048989665927405 -- cost : 193.47006861774977
Epoch : 170 -- m : 4.446498240679196 -- b : 23.145914589718462 -- cost : 192.52353492766377
Epoch : 171 -- m : 4.437281520064627 -- b : 23.242541440258854 -- cost : 191.58281403651148
Epoch : 172 -- m : 4.428093143634059 -- b : 23.338871134213345 -- cost : 190.64787024706214
Epoch : 173 -- m : 4.418933024220611 -- b : 23.434904585427685 -- cost : 189.71866808130704
Epoch : 174 -- m : 4.40980107492547 -- b : 23.53064270493727 -- cost : 188.7951722791127
Epoch : 175 -- m : 4.4006972091170615 -- b : 23.626086400975794 -- cost : 187.87734779688356
Epoch : 176 -- m : 4.39162134043023 -- b : 23.721236578983852 -- cost : 186.96515980623144
Epoch : 177 -- m : 4.382573382765417 -- b : 23.816094141617548 -- cost : 186.05857369265442
Epoch : 178 -- m : 4.373553250287848 -- b : 23.910659988757036 -- cost : 185.15755505422325
Epoch : 179 -- m : 4.364560857426714 -- b : 24.004935017515074 -- cost : 184.26206970027584
Epoch : 180 -- m : 4.355596118874364 -- b : 24.098920122245527 -- cost : 183.37208365011978
Epoch : 181 -- m : 4.3466589495854935 -- b : 24.192616194551857 -- cost : 182.48756313174295
Epoch : 182 -- m : 4.337749264776337 -- b : 24.286024123295572 -- cost : 181.60847458053206
Epoch : 183 -- m : 4.328866979923865 -- b : 24.37914479460467 -- cost : 180.7347846379989
Epoch : 184 -- m : 4.320012010764981 -- b : 24.471979091882037 -- cost : 179.86646015051443
Epoch : 185 -- m : 4.311184273295724 -- b : 24.564527895813825 -- cost : 179.003468168051
Epoch : 186 -- m : 4.3023836837704685 -- b : 24.656792084377816 -- cost : 178.14577594293164
Epoch : 187 -- m : 4.293610158701134 -- b : 24.74877253285175 -- cost : 177.29335092858742
Epoch : 188 -- m : 4.28486361485639 -- b : 24.840470113821617 -- cost : 176.4461607783229
Epoch : 189 -- m : 4.276143969260868 -- b : 24.931885697189948 -- cost : 175.60417334408805
Epoch : 190 -- m : 4.267451139194373 -- b : 25.023020150184063 -- cost : 174.76735667525872
Epoch : 191 -- m : 4.258785042191099 -- b : 25.113874337364297 -- cost : 173.93567901742412
Epoch : 192 -- m : 4.2501455960388475 -- b : 25.2044491206322 -- cost : 173.1091088111818
Epoch : 193 -- m : 4.241532718778248 -- b : 25.294745359238718 -- cost : 172.2876146909402
Epoch : 194 -- m : 4.2329463287019795 -- b : 25.38476390979234 -- cost : 171.4711654837282
Epoch : 195 -- m : 4.224386344353994 -- b : 25.47450562626723 -- cost : 170.6597302080126
Epoch : 196 -- m : 4.215852684528747 -- b : 25.563971360011323 -- cost : 169.85327807252193
Epoch : 197 -- m : 4.2073452682704255 -- b : 25.653161959754403 -- cost : 169.05177847507866
Epoch : 198 -- m : 4.1988640148721785 -- b : 25.742078271616155 -- cost : 168.2552010014373
Epoch : 199 -- m : 4.190408843875353 -- b : 25.830721139114193 -- cost : 167.46351542413083
Epoch : 200 -- m : 4.1819796750687335 -- b : 25.91909140317206 -- cost : 166.67669170132328
Epoch : 201 -- m : 4.173576428487774 -- b : 26.007189902127212 -- cost : 165.89469997567
Epoch : 202 -- m : 4.165199024413845 -- b : 26.095017471738956 -- cost : 165.1175105731845
Epoch : 203 -- m : 4.156847383373476 -- b : 26.182574945196393 -- cost : 164.34509400211246
Epoch : 204 -- m : 4.148521426137602 -- b : 26.269863153126316 -- cost : 163.57742095181283
Epoch : 205 -- m : 4.140221073720811 -- b : 26.356882923601095 -- cost : 162.81446229164524
Epoch : 206 -- m : 4.131946247380593 -- b : 26.443635082146525 -- cost : 162.0561890698647
Epoch : 207 -- m : 4.123696868616596 -- b : 26.53012045174966 -- cost : 161.30257251252323
Epoch : 208 -- m : 4.1154728591698815 -- b : 26.616339852866624 -- cost : 160.55358402237772
Epoch : 209 -- m : 4.107274141022178 -- b : 26.702294103430393 -- cost : 159.80919517780464
Epoch : 210 -- m : 4.099100636395147 -- b : 26.787984018858555 -- cost : 159.06937773172194
Epoch : 211 -- m : 4.090952267749639 -- b : 26.873410412061038 -- cost : 158.3341036105169
Epoch : 212 -- m : 4.082828957784961 -- b : 26.95857409344783 -- cost : 157.6033449129808
Epoch : 213 -- m : 4.074730629438144 -- b : 27.043475870936668 -- cost : 156.87707390925027
Epoch : 214 -- m : 4.066657205883211 -- b : 27.128116549960698 -- cost : 156.15526303975506
Epoch : 215 -- m : 4.058608610530445 -- b : 27.212496933476114 -- cost : 155.43788491417212
Epoch : 216 -- m : 4.05058476702567 -- b : 27.296617821969782 -- cost : 154.72491231038634
Epoch : 217 -- m : 4.042585599249518 -- b : 27.380480013466833 -- cost : 154.01631817345748
Epoch : 218 -- m : 4.034611031316714 -- b : 27.464084303538222 -- cost : 153.31207561459357
Epoch : 219 -- m : 4.026660987575349 -- b : 27.547431485308294 -- cost : 152.61215791013058
Epoch : 220 -- m : 4.018735392606171 -- b : 27.630522349462293 -- cost : 151.91653850051827
Epoch : 221 -- m : 4.010834171221862 -- b : 27.713357684253868 -- cost : 151.22519098931258

In [94]:
y_test

array([53. , 76.1, 90.4, 53.4, 62.8, 70.1, 75.3, 64.4, 57.2, 40.9, 74.1,
       73.5, 32.1, 46.8, 70.8, 68. , 65.7, 64.1, 80.5, 75.1, 72.5, 64.5,
       74.4, 72.7, 64.8, 49.9, 51.2, 91.8, 65.1, 67.4, 70.3, 60.9, 56. ,
       63.5, 65.3, 71.5, 57.8])

In [95]:
y_train

array([68.5, 54.4, 68.7, 56.8, 68.8, 55.4, 48.3, 62.5, 92.4, 79.3, 54.4,
       67.7, 42.7, 68.5, 69. , 60.1, 75.3, 64. , 60.4, 72.1, 48.3, 48.8,
       66.6, 60.4, 63.3, 80. , 59.6, 76. , 63.8, 68.8, 73. , 85.8, 53.8,
       69. , 62.6, 85. , 58.5, 50.9, 76.6, 44.5, 71.2, 45.1, 61.3, 65.6,
       73.9, 69.4, 45.1, 65.9, 68.7, 62.3, 76.1, 70.4, 67.6, 68.8, 70.8,
       61.1, 83.9, 76.6, 68.2, 67. , 55.5, 65.2, 57.4, 68. , 52.9, 65.6,
       67.3, 80.6, 63. , 60.9, 77.5, 47. , 78. , 68.1, 53.6, 84.8, 53.4,
       80.9, 68.3, 75.6, 42.1, 72.9, 62.5, 74.5, 56.1, 77.4, 59.5, 60.8,
       83. , 85.5, 70.9, 61.2, 73.5, 60.3, 73.5, 59.2, 82.6, 82.4, 72.6,
       78. , 45.5, 56.8, 43.6, 66.4, 59.8, 61.2, 48.2, 68.4, 42.2, 64. ,
       72.8, 48.5, 49.8, 63.7, 58.5, 72.1, 38.1, 52.4, 71.4, 78. , 48.2,
       53.8, 71.2, 72.2, 42.5, 71.2, 62.4, 58.3, 56.1, 46.5, 71.5, 59.5,
       68.1, 60.3, 70.6, 74.1, 86. , 65.3, 65.7, 65.7, 77.7, 64. , 78. ,
       79.1, 52.3, 62.3, 88.4])

In [96]:
x_test_pred =model.predict(x_test)

In [97]:
x_test_pred

array([52.41121795, 65.19978543, 89.49806366, 59.31704439, 59.82858709,
       62.13052924, 65.19978543, 70.82675513, 57.27087359, 48.06310501,
       78.24412427, 66.73441353, 46.78424826, 49.85350445, 73.38446863,
       61.36321519, 62.13052924, 56.75933089, 91.03269175, 66.47864218,
       59.06127304, 50.1092758 , 74.15178267, 65.71132813, 58.03818764,
       54.2016174 , 45.50539151, 91.2884631 , 55.2247028 , 57.27087359,
       54.7131601 , 49.34196175, 57.01510224, 51.89967525, 46.52847691,
       63.15361464, 59.06127304])

In [98]:
y_test

array([53. , 76.1, 90.4, 53.4, 62.8, 70.1, 75.3, 64.4, 57.2, 40.9, 74.1,
       73.5, 32.1, 46.8, 70.8, 68. , 65.7, 64.1, 80.5, 75.1, 72.5, 64.5,
       74.4, 72.7, 64.8, 49.9, 51.2, 91.8, 65.1, 67.4, 70.3, 60.9, 56. ,
       63.5, 65.3, 71.5, 57.8])

In [99]:
model.cost(x_test,y_test)

np.float64(36.24146180229899)

In [100]:
model.history

[(np.float64(5.232264870541083),
  np.float64(1.5682935431155702),
  np.float64(535.0446231973267)),
 (np.float64(6.18906570358156),
  np.float64(1.8236518221462896),
  np.float64(473.7624720826851)),
 (np.float64(6.396161179056569),
  np.float64(2.0069950614595276),
  np.float64(468.04332702241436)),
 (np.float64(6.431688391578847),
  np.float64(2.173470231125182),
  np.float64(465.2507313131026)),
 (np.float64(6.427980759853007),
  np.float64(2.3357014582561906),
  np.float64(462.62677757986813)),
 (np.float64(6.415328821958863),
  np.float64(2.4965795383303546),
  np.float64(460.0268751444302)),
 (np.float64(6.400665862704679),
  np.float64(2.656767338099107),
  np.float64(457.4433549416931)),
 (np.float64(6.385578774774345),
  np.float64(2.8164177557166297),
  np.float64(454.87572229485187)),
 (np.float64(6.370430680991576),
  np.float64(2.975566955734076),
  np.float64(452.32385898934876)),
 (np.float64(6.355304587939787),
  np.float64(3.1342243792067337),
  np.float64(449.7876671016402)),
 (np.float64(6.340219384929229),
  np.float64(3.2923933466994897),
  np.float64(447.26705033462855)),
 (np.float64(6.3251792853937685),
  np.float64(3.4500757742527397),
  np.float64(444.76191303629747)),
 (np.float64(6.310185143850283),
  np.float64(3.6072732528612335),
  np.float64(442.27216014485754)),
 (np.float64(6.29523704630951),
  np.float64(3.7639872955738864),
  np.float64(439.7976971824549)),
 (np.float64(6.280334903210858),
  np.float64(3.9202193940649512),
  np.float64(437.3384302514454)),
 (np.float64(6.265478585142056),
  np.float64(4.075971031593824),
  np.float64(434.8942660308241)),
 (np.float64(6.250667953903859),
  np.float64(4.231243685982326),
  np.float64(432.4651117726839)),
 (np.float64(6.235902869619626),
  np.float64(4.386038830306999),
  np.float64(430.05087529869587)),
 (np.float64(6.221183192361645),
  np.float64(4.540357933068329),
  np.float64(427.65146499661114)),
 (np.float64(6.206508782522369),
  np.float64(4.694202458240213),
  np.float64(425.266789816785)),
 (np.float64(6.191879500898376),
  np.float64(4.847573865291985),
  np.float64(422.8967592687217)),
 (np.float64(6.177295208708563),
  np.float64(5.000473609204123),
  np.float64(420.54128341764044)),
 (np.float64(6.1627557675973),
  np.float64(5.152903140482476),
  np.float64(418.2002728810628)),
 (np.float64(6.148261039634141),
  np.float64(5.304863905172122),
  np.float64(415.87363882542104)),
 (np.float64(6.1338108873127455),
  np.float64(5.456357344871112),
  np.float64(413.56129296268676)),
 (np.float64(6.119405173549633),
  np.float64(5.607384896744145),
  np.float64(411.2631475470218)),
 (np.float64(6.10504376168289),
  np.float64(5.75794799353621),
  np.float64(408.9791153714468)),
 (np.float64(6.090726515470883),
  np.float64(5.9080480635861745),
  np.float64(406.7091097645335)),
 (np.float64(6.076453299090956),
  np.float64(6.057686530840332),
  np.float64(404.4530445871151)),
 (np.float64(6.062223977138154),
  np.float64(6.2068648148659165),
  np.float64(402.2108342290179)),
 (np.float64(6.04803841462393),
  np.float64(6.3555843308645645),
  np.float64(399.9823936058123)),
 (np.float64(6.033896476974866),
  np.float64(6.503846489685744),
  np.float64(397.7676381555848)),
 (np.float64(6.019798030031402),
  np.float64(6.651652697840135),
  np.float64(395.5664838357281)),
 (np.float64(6.005742940046555),
  np.float64(6.799004357512978),
  np.float64(393.3788471197531)),
 (np.float64(5.991731073684656),
  np.float64(6.94590286657737),
  np.float64(391.20464499411867)),
 (np.float64(5.9777622980200835),
  np.float64(7.092349618607529),
  np.float64(389.0437949550816)),
 (np.float64(5.963836480536),
  np.float64(7.238346002892015),
  np.float64(386.89621500556615)),
 (np.float64(5.9499534891231),
  np.float64(7.383893404446906),
  np.float64(384.76182365205227)),
 (np.float64(5.936113192078352),
  np.float64(7.528993204028941),
  np.float64(382.6405399014835)),
 (np.float64(5.922315458103751),
  np.float64(7.673646778148619),
  np.float64(380.53228325819293)),
 (np.float64(5.908560156305073),
  np.float64(7.817855499083253),
  np.float64(378.4369737208494)),
 (np.float64(5.894847156190635),
  np.float64(7.961620734889992),
  np.float64(376.3545317794212)),
 (np.float64(5.88117632767005),
  np.float64(8.1049438494188),
  np.float64(374.28487841215923)),
 (np.float64(5.867547541053004),
  np.float64(8.247826202325392),
  np.float64(372.22793508259826)),
 (np.float64(5.853960667048016),
  np.float64(8.39026914908413),
  np.float64(370.18362373657664)),
 (np.float64(5.840415576761216),
  np.float64(8.532274041000889),
  np.float64(368.15186679927456)),
 (np.float64(5.826912141695121),
  np.float64(8.673842225225872),
  np.float64(366.13258717227035)),
 (np.float64(5.813450233747417),
  np.float64(8.81497504476639),
  np.float64(364.1257082306147)),
 (np.float64(5.800029725209744),
  np.float64(8.955673838499603),
  np.float64(362.1311538199232)),
 (np.float64(5.786650488766481),
  np.float64(9.095939941185224),
  np.float64(360.14884825348616)),
 (np.float64(5.773312397493543),
  np.float64(9.235774683478173),
  np.float64(358.17871630939715)),
 (np.float64(5.760015324857173),
  np.float64(9.375179391941213),
  np.float64(356.22068322769803)),
 (np.float64(5.746759144712746),
  np.float64(9.514155389057525),
  np.float64(354.2746747075422)),
 (np.float64(5.733543731303566),
  np.float64(9.652703993243257),
  np.float64(352.34061690437545)),
 (np.float64(5.720368959259679),
  np.float64(9.790826518860033),
  np.float64(350.41843642713354)),
 (np.float64(5.707234703596681),
  np.float64(9.928524276227419),
  np.float64(348.50806033545683)),
 (np.float64(5.694140839714532),
  np.float64(10.065798571635353),
  np.float64(346.60941613692336)),
 (np.float64(5.681087243396374),
  np.float64(10.202650707356543),
  np.float64(344.7224317842973)),
 (np.float64(5.668073790807355),
  np.float64(10.339081981658815),
  np.float64(342.84703567279536)),
 (np.float64(5.655100358493452),
  np.float64(10.47509368881743),
  np.float64(340.9831566373693)),
 (np.float64(5.642166823380298),
  np.float64(10.61068711912737),
  np.float64(339.13072395000563)),
 (np.float64(5.629273062772018),
  np.float64(10.745863558915564),
  np.float64(337.28966731704185)),
 (np.float64(5.616418954350065),
  np.float64(10.880624290553104),
  np.float64(335.4599168764988)),
 (np.float64(5.603604376172057),
  np.float64(11.014970592467407),
  np.float64(333.6414031954299)),
 (np.float64(5.59082920667062),
  np.float64(11.148903739154338),
  np.float64(331.83405726728614)),
 (np.float64(5.57809332465224),
  np.float64(11.282425001190308),
  np.float64(330.03781050929746)),
 (np.float64(5.565396609296105),
  np.float64(11.415535645244322),
  np.float64(328.2525947598706)),
 (np.float64(5.552738940152967),
  np.float64(11.548236934089998),
  np.float64(326.4783422760023)),
 (np.float64(5.5401201971439935),
  np.float64(11.680530126617544),
  np.float64(324.714985730709)),
 (np.float64(5.527540260559631),
  np.float64(11.812416477845707),
  np.float64(322.9624582104713)),
 (np.float64(5.514999011058468),
  np.float64(11.943897238933669),
  np.float64(321.2206932126961)),
 (np.float64(5.502496329666107),
  np.float64(12.074973657192926),
  np.float64(319.48962464319135)),
 (np.float64(5.490032097774027),
  np.float64(12.205646976099114),
  np.float64(317.7691868136595)),
 (np.float64(5.47760619713847),
  np.float64(12.335918435303808),
  np.float64(316.05931443920406)),
 (np.float64(5.465218509879307),
  np.float64(12.465789270646285),
  np.float64(314.3599426358524)),
 (np.float64(5.45286891847893),
  np.float64(12.59526071416524),
  np.float64(312.6710069180937)),
 (np.float64(5.440557305781132),
  np.float64(12.724333994110484),
  np.float64(310.992443196432)),
 (np.float64(5.428283554989997),
  np.float64(12.85301033495459),
  np.float64(309.3241877749539)),
 (np.float64(5.4160475496687885),
  np.float64(12.981290957404505),
  np.float64(307.6661773489119)),
 (np.float64(5.403849173738852),
  np.float64(13.109177078413143),
  np.float64(306.0183490023219)),
 (np.float64(5.391688311478507),
  np.float64(13.23666991119092),
  np.float64(304.38064020557584)),
 (np.float64(5.379564847521953),
  np.float64(13.36377066521726),
  np.float64(302.75298881306924)),
 (np.float64(5.367478666858174),
  np.float64(13.490480546252082),
  np.float64(301.1353330608422)),
 (np.float64(5.355429654829847),
  np.float64(13.616800756347226),
  np.float64(299.52761156423657)),
 (np.float64(5.343417697132255),
  np.float64(13.742732493857865),
  np.float64(297.92976331556594)),
 (np.float64(5.331442679812202),
  np.float64(13.868276953453869),
  np.float64(296.3417276818009)),
 (np.float64(5.319504489266933),
  np.float64(13.993435326131136),
  np.float64(294.7634444022682)),
 (np.float64(5.307603012243056),
  np.float64(14.1182087992229),
  np.float64(293.19485358636393)),
 (np.float64(5.295738135835464),
  np.float64(14.242598556410984),
  np.float64(291.635895711281)),
 (np.float64(5.283909747486271),
  np.float64(14.366605777737036),
  np.float64(290.0865116197504)),
 (np.float64(5.2721177349837385),
  np.float64(14.49023163961372),
  np.float64(288.5466425177964)),
 (np.float64(5.260361986461214),
  np.float64(14.61347731483588),
  np.float64(287.01622997250536)),
 (np.float64(5.248642390396065),
  np.float64(14.73634397259166),
  np.float64(285.49521590980885)),
 (np.float64(5.23695883560863),
  np.float64(14.858832778473603),
  np.float64(283.9835426122792)),
 (np.float64(5.225311211261154),
  np.float64(14.980944894489705),
  np.float64(282.48115271694013)),
 (np.float64(5.213699406856744),
  np.float64(15.102681479074434),
  np.float64(280.9879892130891)),
 (np.float64(5.2021233122383155),
  np.float64(15.224043687099728),
  np.float64(279.50399544013516)),
 (np.float64(5.190582817587553),
  np.float64(15.345032669885947),
  np.float64(278.02911508544753)),
 (np.float64(5.179077813423864),
  np.float64(15.465649575212794),
  np.float64(276.56329218221964)),
 (np.float64(5.167608190603341),
  np.float64(15.585895547330203),
  np.float64(275.10647110734504)),
 (np.float64(5.156173840317727),
  np.float64(15.705771726969198),
  np.float64(273.65859657930685)),
 (np.float64(5.144774654093386),
  np.float64(15.825279251352713),
  np.float64(272.2196136560797)),
 (np.float64(5.133410523790266),
  np.float64(15.944419254206377),
  np.float64(270.7894677330452)),
 (np.float64(5.1220813416008815),
  np.float64(16.063192865769274),
  np.float64(269.36810454091983)),
 (np.float64(5.110787000049287),
  np.float64(16.181601212804665),
  np.float64(267.9554701436953)),
 (np.float64(5.0995273919900574),
  np.float64(16.299645418610677),
  np.float64(266.5515109365921)),
 (np.float64(5.0883024106072705),
  np.float64(16.41732660303095),
  np.float64(265.1561736440255)),
 (np.float64(5.077111949413498),
  np.float64(16.534645882465277),
  np.float64(263.7694053175837)),
 (np.float64(5.065955902248792),
  np.float64(16.65160436988018),
  np.float64(262.39115333401855)),
 (np.float64(5.054834163279676),
  np.float64(16.768203174819476),
  np.float64(261.02136539324914)),
 (np.float64(5.043746626998144),
  np.float64(16.884443403414807),
  np.float64(259.6599895163764)),
 (np.float64(5.0326931882206605),
  np.float64(17.000326158396124),
  np.float64(258.3069740437113)),
 (np.float64(5.0216737420871596),
  np.float64(17.11585253910215),
  np.float64(256.96226763281464)),
 (np.float64(5.010688184060052),
  np.float64(17.231023641490815),
  np.float64(255.62581925654806)),
 (np.float64(4.999736409923231),
  np.float64(17.345840558149643),
  np.float64(254.2975782011384)),
 (np.float64(4.98881831578109),
  np.float64(17.460304378306134),
  np.float64(252.97749406425305)),
 (np.float64(4.97793379805753),
  np.float64(17.574416187838075),
  np.float64(251.66551675308725)),
 (np.float64(4.967082753494977),
  np.float64(17.688177069283864),
  np.float64(250.36159648246328)),
 (np.float64(4.95626507915341),
  np.float64(17.801588101852754),
  np.float64(249.06568377294158)),
 (np.float64(4.945480672409377),
  np.float64(17.914650361435122),
  np.float64(247.7777294489426)),
 (np.float64(4.934729430955024),
  np.float64(18.027364920612644),
  np.float64(246.49768463688127)),
 (np.float64(4.924011252797124),
  np.float64(18.139732848668494),
  np.float64(245.22550076331217)),
 (np.float64(4.913326036256111),
  np.float64(18.25175521159748),
  np.float64(243.96112955308624)),
 (np.float64(4.902673679965112),
  np.float64(18.36343307211615),
  np.float64(242.70452302751923)),
 (np.float64(4.892054082868991),
  np.float64(18.474767489672878),
  np.float64(241.45563350257078)),
 (np.float64(4.881467144223384),
  np.float64(18.585759520457927),
  np.float64(240.21441358703493)),
 (np.float64(4.870912763593747),
  np.float64(18.696410217413447),
  np.float64(238.98081618074195)),
 (np.float64(4.860390840854404),
  np.float64(18.80672063024348),
  np.float64(237.75479447277118)),
 (np.float64(4.849901276187592),
  np.float64(18.91669180542391),
  np.float64(236.53630193967436)),
 (np.float64(4.839443970082521),
  np.float64(19.026324786212395),
  np.float64(235.32529234371032)),
 (np.float64(4.829018823334424),
  np.float64(19.135620612658265),
  np.float64(234.12171973109065)),
 (np.float64(4.818625737043622),
  np.float64(19.24458032161238),
  np.float64(232.92553843023566)),
 (np.float64(4.808264612614578),
  np.float64(19.353204946736973),
  np.float64(231.7367030500414)),
 (np.float64(4.797935351754969),
  np.float64(19.461495518515463),
  np.float64(230.55516847815707)),
 (np.float64(4.787637856474748),
  np.float64(19.569453064262213),
  np.float64(229.3808898792735)),
 (np.float64(4.777372029085219),
  np.float64(19.67707860813229),
  np.float64(228.21382269342138)),
 (np.float64(4.767137772198106),
  np.float64(19.784373171131183),
  np.float64(227.05392263428055)),
 (np.float64(4.756934988724634),
  np.float64(19.89133777112447),
  np.float64(225.90114568749962)),
 (np.float64(4.746763581874602),
  np.float64(19.997973422847494),
  np.float64(224.75544810902556)),
 (np.float64(4.7366234551554705),
  np.float64(20.10428113791498),
  np.float64(223.61678642344387)),
 (np.float64(4.726514512371442),
  np.float64(20.21026192483064),
  np.float64(222.4851174223287)),
 (np.float64(4.71643665762255),
  np.float64(20.315916788996724),
  np.float64(221.36039816260336)),
 (np.float64(4.70638979530375),
  np.float64(20.421246732723574),
  np.float64(220.24258596491092)),
 (np.float64(4.696373830104011),
  np.float64(20.526252755239128),
  np.float64(219.1316384119942)),
 (np.float64(4.686388667005413),
  np.float64(20.630935852698393),
  np.float64(218.02751334708674)),
 (np.float64(4.676434211282243),
  np.float64(20.735297018192902),
  np.float64(216.93016887231272)),
 (np.float64(4.6665103685001),
  np.float64(20.839337241760138),
  np.float64(215.839563347097)),
 (np.float64(4.656617044514996),
  np.float64(20.943057510392915),
  np.float64(214.75565538658543)),
 (np.float64(4.646754145472465),
  np.float64(21.04645880804875),
  np.float64(213.6784038600741)),
 (np.float64(4.636921577806669),
  np.float64(21.1495421156592),
  np.float64(212.6077678894485)),
 (np.float64(4.6271192482395165),
  np.float64(21.252308411139158),
  np.float64(211.5437068476327)),
 (np.float64(4.617347063779771),
  np.float64(21.35475866939613),
  np.float64(210.4861803570474)),
 (np.float64(4.607604931722176),
  np.float64(21.456893862339495),
  np.float64(209.43514828807764)),
 (np.float64(4.597892759646567),
  np.float64(21.55871495888972),
  np.float64(208.39057075755034)),
 (np.float64(4.588210455417002),
  np.float64(21.660222924987547),
  np.float64(207.3524081272206)),
 (np.float64(4.578557927180884),
  np.float64(21.761418723603164),
  np.float64(206.32062100226773)),
 (np.float64(4.568935083368091),
  np.float64(21.86230331474533),
  np.float64(205.29517022980025)),
 (np.float64(4.559341832690105),
  np.float64(21.962877655470493),
  np.float64(204.27601689737014)),
 (np.float64(4.54977808413915),
  np.float64(22.063142699891866),
  np.float64(203.26312233149645)),
 (np.float64(4.540243746987323),
  np.float64(22.16309939918848),
  np.float64(202.25644809619735)),
 (np.float64(4.530738730785739),
  np.float64(22.262748701614193),
  np.float64(201.25595599153215)),
 (np.float64(4.52126294536367),
  np.float64(22.36209155250671),
  np.float64(200.26160805215133)),
 (np.float64(4.51181630082769),
  np.float64(22.46112889429653),
  np.float64(199.27336654585602)),
 (np.float64(4.502398707560824),
  np.float64(22.5598616665159),
  np.float64(198.29119397216624)),
 (np.float64(4.493010076221691),
  np.float64(22.658290805807727),
  np.float64(197.31505306089772)),
 (np.float64(4.483650317743667),
  np.float64(22.75641724593445),
  np.float64(196.3449067707479)),
 (np.float64(4.474319343334032),
  np.float64(22.854241917786915),
  np.float64(195.38071828789006)),
 (np.float64(4.465017064473131),
  np.float64(22.951765749393196),
  np.float64(194.42245102457636)),
 (np.float64(4.455743392913534),
  np.float64(23.048989665927405),
  np.float64(193.47006861774977)),
 (np.float64(4.446498240679196),
  np.float64(23.145914589718462),
  np.float64(192.52353492766377)),
 (np.float64(4.437281520064627),
  np.float64(23.242541440258854),
  np.float64(191.58281403651148)),
 (np.float64(4.428093143634059),
  np.float64(23.338871134213345),
  np.float64(190.64787024706214)),
 (np.float64(4.418933024220611),
  np.float64(23.434904585427685),
  np.float64(189.71866808130704)),
 (np.float64(4.40980107492547),
  np.float64(23.53064270493727),
  np.float64(188.7951722791127)),
 (np.float64(4.4006972091170615),
  np.float64(23.626086400975794),
  np.float64(187.87734779688356)),
 (np.float64(4.39162134043023),
  np.float64(23.721236578983852),
  np.float64(186.96515980623144)),
 (np.float64(4.382573382765417),
  np.float64(23.816094141617548),
  np.float64(186.05857369265442)),
 (np.float64(4.373553250287848),
  np.float64(23.910659988757036),
  np.float64(185.15755505422325)),
 (np.float64(4.364560857426714),
  np.float64(24.004935017515074),
  np.float64(184.26206970027584)),
 (np.float64(4.355596118874364),
  np.float64(24.098920122245527),
  np.float64(183.37208365011978)),
 (np.float64(4.3466589495854935),
  np.float64(24.192616194551857),
  np.float64(182.48756313174295)),
 (np.float64(4.337749264776337),
  np.float64(24.286024123295572),
  np.float64(181.60847458053206)),
 (np.float64(4.328866979923865),
  np.float64(24.37914479460467),
  np.float64(180.7347846379989)),
 (np.float64(4.320012010764981),
  np.float64(24.471979091882037),
  np.float64(179.86646015051443)),
 (np.float64(4.311184273295724),
  np.float64(24.564527895813825),
  np.float64(179.003468168051)),
 (np.float64(4.3023836837704685),
  np.float64(24.656792084377816),
  np.float64(178.14577594293164)),
 (np.float64(4.293610158701134),
  np.float64(24.74877253285175),
  np.float64(177.29335092858742)),
 (np.float64(4.28486361485639),
  np.float64(24.840470113821617),
  np.float64(176.4461607783229)),
 (np.float64(4.276143969260868),
  np.float64(24.931885697189948),
  np.float64(175.60417334408805)),
 (np.float64(4.267451139194373),
  np.float64(25.023020150184063),
  np.float64(174.76735667525872)),
 (np.float64(4.258785042191099),
  np.float64(25.113874337364297),
  np.float64(173.93567901742412)),
 (np.float64(4.2501455960388475),
  np.float64(25.2044491206322),
  np.float64(173.1091088111818)),
 (np.float64(4.241532718778248),
  np.float64(25.294745359238718),
  np.float64(172.2876146909402)),
 (np.float64(4.2329463287019795),
  np.float64(25.38476390979234),
  np.float64(171.4711654837282)),
 (np.float64(4.224386344353994),
  np.float64(25.47450562626723),
  np.float64(170.6597302080126)),
 (np.float64(4.215852684528747),
  np.float64(25.563971360011323),
  np.float64(169.85327807252193)),
 (np.float64(4.2073452682704255),
  np.float64(25.653161959754403),
  np.float64(169.05177847507866)),
 (np.float64(4.1988640148721785),
  np.float64(25.742078271616155),

In [120]:
path = (r"C:\Users\HP\Desktop\AI_project\week-05-visualization-first-models-and-ML\datasets\students.csv")

In [121]:
df = pd.read_csv(path,usecols=['study_hours' ,"attendance" ])

In [122]:
df

     study_hours  attendance
0            8.1        87.5
1            5.2        77.4
2            4.0        96.9
3            2.5       100.0
4            7.7        87.8
..           ...         ...
179          5.5        68.6
180          3.5        70.1
181          1.4        82.0
182          7.9        97.8
183          6.3        75.5

[184 rows x 2 columns]

In [123]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  179 non-null    float64
 1   attendance   168 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB

In [124]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].median())

In [126]:
df['attendance'] = df['attendance'].fillna(df['attendance'].median())

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  184 non-null    float64
 1   attendance   184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB

In [128]:
x_train =np.array(df['study_hours'].iloc[0:147])
y_train =np.array(df['attendance'].iloc[0:147])
y_test =np.array(df['attendance'].iloc[147])
y_test =np.array(df['attendance'].iloc[147])

In [129]:
class LinearRegression:
    count = 0
    def __init__(self, m=0, b=0, alpha=0):
        self.alpha = alpha
        self.m = m
        self.b = b
        self.history = []

    def predict(self, x) :
        return self.m * x + self.b

    def cost(self, x, y):
        y_hat = self.predict(x)
        error = y_hat - y
        loss = (1/(2*len(x))) * np.sum(error**2)
        return loss

    def gradeint(self,x ,y):
        y_hat = self.predict(x)
        error = y_hat - y
        gm = np.sum (error* x) /len(x)
        gb = np.sum(error) /len(x)
        return gm,gb

    def run_epoch(self,x,y):
        gm, gb = self.gradeint(x,y)
        self.m -= self.alpha * gm
        self.b -= self.alpha * gb
        loss = self.cost(x,y)
        self.history.append((self.m, self.b, loss))
        self.count += 1
        print(f"Epoch : {self.count} -- m : {self.m} -- b : {self.b} -- cost : {loss}")


    def fit(self,epoch ,x,y):
        for i in range( 1,epoch+1):
            self.run_epoch(x,y)

In [ ]:

model1 = LinearRegression(0,0,0.01)

In [145]:
for e in range(8,1000):
    model1.run_epoch(x_train,y_train)

Epoch : 1 -- m : 5.897529931972789 -- b : 0.822639455782313 -- cost : 1241.337298609956
Epoch : 2 -- m : 7.252287776214077 -- b : 1.210624995599056 -- cost : 1116.3851879404451
Epoch : 3 -- m : 7.549107742124642 -- b : 1.4967733934432053 -- cost : 1103.3907090040325
Epoch : 4 -- m : 7.59959549461193 -- b : 1.758598406508482 -- cost : 1096.5073189891607
Epoch : 5 -- m : 7.592771009239708 -- b : 2.0141545958295866 -- cost : 1089.9935793066356
Epoch : 6 -- m : 7.572656206602281 -- b : 2.267648675332455 -- cost : 1083.5378338019384
Epoch : 7 -- m : 7.549503461926583 -- b : 2.5200622374228336 -- cost : 1077.1229435232058
Epoch : 8 -- m : 7.525700340574561 -- b : 2.771625749083859 -- cost : 1070.7477458162612
Epoch : 9 -- m : 7.501802721418691 -- b : 3.022394737035422 -- cost : 1064.4119460340519
Epoch : 10 -- m : 7.477939890425229 -- b : 3.2723839792843923 -- cost : 1058.1152980419831
Epoch : 11 -- m : 7.45414178209236 -- b : 3.521598757890666 -- cost : 1051.8575597590273
Epoch : 12 -- m : 7.430415192848569 -- b : 3.770042137646047 -- cost : 1045.6384907374488
Epoch : 13 -- m : 7.406761530888067 -- b : 4.017716661271033 -- cost : 1039.457852022795
Epoch : 14 -- m : 7.383180950044438 -- b : 4.264624744237851 -- cost : 1033.3154061376183
Epoch : 15 -- m : 7.359673312553859 -- b : 4.510768766740899 -- cost : 1027.2109170719698
Epoch : 16 -- m : 7.336238413277659 -- b : 4.756151095133796 -- cost : 1021.1441502743078
Epoch : 17 -- m : 7.312876031921308 -- b : 5.000774086939408 -- cost : 1015.114872642486
Epoch : 18 -- m : 7.289585945194394 -- b : 5.244640092034017 -- cost : 1009.1228525147976
Epoch : 19 -- m : 7.2663679296409756 -- b : 5.487751452940404 -- cost : 1003.167859661072
Epoch : 20 -- m : 7.243221762297126 -- b : 5.730110504913354 -- cost : 997.2496652738309
Epoch : 21 -- m : 7.22014722084242 -- b : 5.971719575976763 -- cost : 991.3680419594954
Epoch : 22 -- m : 7.197144083633585 -- b : 6.212580986949417 -- cost : 985.5227637296501
Epoch : 23 -- m : 7.174212129710706 -- b : 6.452697051468077 -- cost : 979.713605992359
Epoch : 24 -- m : 7.1513511387970405 -- b : 6.692070076009892 -- cost : 973.9403455435364
Epoch : 25 -- m : 7.128560891297357 -- b : 6.930702359914598 -- cost : 968.202760558371
Epoch : 26 -- m : 7.10584116829593 -- b : 7.168596195406611 -- cost : 962.5006305828024
Epoch : 27 -- m : 7.083191751554463 -- b : 7.405753867617052 -- cost : 956.833736525051
Epoch : 28 -- m : 7.060612423509998 -- b : 7.642177654605695 -- cost : 951.2018606471995
Epoch : 29 -- m : 7.038102967272821 -- b : 7.877869827382851 -- cost : 945.6047865568272
Epoch : 30 -- m : 7.015663166624389 -- b : 8.11283264993118 -- cost : 940.0422991986954
Epoch : 31 -- m : 6.993292806015246 -- b : 8.347068379227442 -- cost : 934.5141848464839
Epoch : 32 -- m : 6.970991670562955 -- b : 8.580579265264175 -- cost : 929.0202310945804
Epoch : 33 -- m : 6.948759546050033 -- b : 8.813367551071305 -- cost : 923.5602268499177
Epoch : 34 -- m : 6.926596218921892 -- b : 9.045435472737696 -- cost : 918.1339623238638
Epoch : 35 -- m : 6.9045014762847945 -- b : 9.276785259432627 -- cost : 912.7412290241606
Epoch : 36 -- m : 6.882475105903798 -- b : 9.507419133427204 -- cost : 907.3818197469147
Epoch : 37 -- m : 6.860516896200724 -- b : 9.737339310115711 -- cost : 902.0555285686337
Epoch : 38 -- m : 6.8386266362521235 -- b : 9.966547998036884 -- cost : 896.7621508383154
Epoch : 39 -- m : 6.816804115787251 -- b : 10.19504739889513 -- cost : 891.5014831695846
Epoch : 40 -- m : 6.795049125186044 -- b : 10.42283970758167 -- cost : 886.2733234328781
Epoch : 41 -- m : 6.77336145547711 -- b : 10.649927112195632 -- cost : 881.0774707476779
Epoch : 42 -- m : 6.7517408983357186 -- b : 10.876311794065062 -- cost : 875.913725474794
Epoch : 43 -- m : 6.730187246081803 -- b : 11.101995927767879 -- cost : 870.7818892086923
Epoch : 44 -- m : 6.70870029167796 -- b : 11.32698168115276 -- cost : 865.6817647698728
Epoch : 45 -- m : 6.687279828727469 -- b : 11.551271215359975 -- cost : 860.6131561972911
Epoch : 46 -- m : 6.665925651472299 -- b : 11.774866684842129 -- cost : 855.575868740832
Epoch : 47 -- m : 6.644637554791142 -- b : 11.99777023738487 -- cost : 850.569708853825
Epoch : 48 -- m : 6.623415334197437 -- b : 12.219984014127517 -- cost : 845.5944841856068
Epoch : 49 -- m : 6.602258785837408 -- b : 12.441510149583626 -- cost : 840.6500035741328
Epoch : 50 -- m : 6.581167706488106 -- b : 12.662350771661492 -- cost : 835.7360770386306
Epoch : 51 -- m : 6.5601418935554525 -- b : 12.882508001684592 -- cost : 830.852515772301
Epoch : 52 -- m : 6.539181145072302 -- b : 13.101983954411958 -- cost : 825.9991321350628
Epoch : 53 -- m : 6.518285259696493 -- b : 13.320780738058495 -- cost : 821.1757396463448
Epoch : 54 -- m : 6.497454036708921 -- b : 13.53890045431523 -- cost : 816.3821529779182
Epoch : 55 -- m : 6.476687276011605 -- b : 13.7563451983695 -- cost : 811.6181879467786
Epoch : 56 -- m : 6.455984778125769 -- b : 13.973117058925075 -- cost : 806.8836615080668
Epoch : 57 -- m : 6.4353463441899255 -- b : 14.189218118222227 -- cost : 802.1783917480367
Epoch : 58 -- m : 6.414771775957964 -- b : 14.404650452057728 -- cost : 797.5021978770662
Epoch : 59 -- m : 6.394260875797245 -- b : 14.619416129804788 -- cost : 792.8549002227097
Epoch : 60 -- m : 6.373813446686707 -- b : 14.833517214432938 -- cost : 788.236320222795
Epoch : 61 -- m : 6.3534292922149715 -- b : 15.046955762527839 -- cost : 783.6462804185625
Epoch : 62 -- m : 6.333108216578451 -- b : 15.259733824311043 -- cost : 779.0846044478471
Epoch : 63 -- m : 6.312850024579478 -- b : 15.471853443659686 -- cost : 774.5511170383012
Epoch : 64 -- m : 6.292654521624421 -- b : 15.683316658126115 -- cost : 770.0456440006606
Epoch : 65 -- m : 6.272521513721822 -- b : 15.894125498957466 -- cost : 765.5680122220516
Epoch : 66 -- m : 6.252450807480528 -- b : 16.104281991115176 -- cost : 761.1180496593395
Epoch : 67 -- m : 6.232442210107838 -- b : 16.31378815329443 -- cost : 756.6955853325185
Epoch : 68 -- m : 6.212495529407645 -- b : 16.522645997943552 -- cost : 752.3004493181414
Epoch : 69 -- m : 6.192610573778598 -- b : 16.73085753128334 -- cost : 747.9324727427918
Epoch : 70 -- m : 6.172787152212254 -- b : 16.93842475332634 -- cost : 743.5914877765945
Epoch : 71 -- m : 6.1530250742912465 -- b : 17.145349657896045 -- cost : 739.2773276267676
Epoch : 72 -- m : 6.133324150187457 -- b : 17.351634232646052 -- cost : 734.9898265312135
Epoch : 73 -- m : 6.113684190660192 -- b : 17.557280459079166 -- cost : 730.7288197521501
Epoch : 74 -- m : 6.09410500705436 -- b : 17.76229031256642 -- cost : 726.4941435697809
Epoch : 75 -- m : 6.074586411298667 -- b : 17.96666576236606 -- cost : 722.2856352760052
Epoch : 76 -- m : 6.055128215903805 -- b : 18.170408771642443 -- cost : 718.1031331681645
Epoch : 77 -- m : 6.035730233960653 -- b : 18.37352129748492 -- cost : 713.9464765428322
Epoch : 78 -- m : 6.016392279138478 -- b : 18.576005290926616 -- cost : 709.815505689636
Epoch : 79 -- m : 5.997114165683153 -- b : 18.77786269696318 -- cost : 705.7100618851238
Epoch : 80 -- m : 5.977895708415365 -- b : 18.979095454571464 -- cost : 701.6299873866636
Epoch : 81 -- m : 5.958736722728838 -- b : 19.17970549672815 -- cost : 697.5751254263832
Epoch : 82 -- m : 5.939637024588561 -- b : 19.379694750428317 -- cost : 693.545320205147
Epoch : 83 -- m : 5.920596430529023 -- b : 19.579065136703953 -- cost : 689.5404168865687
Epoch : 84 -- m : 5.901614757652443 -- b : 19.777818570642403 -- cost : 685.5602615910628
Epoch : 85 -- m : 5.882691823627023 -- b : 19.97595696140477 -- cost : 681.604701389933
Epoch : 86 -- m : 5.863827446685187 -- b : 20.17348221224425 -- cost : 677.673584299494
Epoch : 87 -- m : 5.845021445621842 -- b : 20.370396220524412 -- cost : 673.7667592752344
Epoch : 88 -- m : 5.826273639792633 -- b : 20.566700877737436 -- cost : 669.8840762060107
Epoch : 89 -- m : 5.80758384911221 -- b : 20.762398069522266 -- cost : 666.0253859082821
Epoch : 90 -- m : 5.7889518940524995 -- b : 20.957489675682734 -- cost : 662.190540120376
Epoch : 91 -- m : 5.770377595640976 -- b : 21.151977570205606 -- cost : 658.3793914967931
Epoch : 92 -- m : 5.751860775458947 -- b : 21.345863621278596 -- cost : 654.5917936025461
Epoch : 93 -- m : 5.7334012556398335 -- b : 21.539149691308307 -- cost : 650.8276009075307
Epoch : 94 -- m : 5.714998858867471 -- b : 21.73183763693811 -- cost : 647.0866687809379
Epoch : 95 -- m : 5.696653408374396 -- b : 21.92392930906599 -- cost : 643.3688534856936
Epoch : 96 -- m : 5.678364727940154 -- b : 22.115426552862328 -- cost : 639.674012172937
Epoch : 97 -- m : 5.6601326418896045 -- b : 22.30633120778761 -- cost : 636.0020028765324
Epoch : 98 -- m : 5.641956975091237 -- b : 22.496645107610114 -- cost : 632.3526845076141
Epoch : 99 -- m : 5.623837552955481 -- b : 22.686370080423504 -- cost : 628.7259168491647
Epoch : 100 -- m : 5.60577420143304 -- b : 22.875507948664414 -- cost : 625.1215605506288
Epoch : 101 -- m : 5.587766747013211 -- b : 23.064060529129932 -- cost : 621.5394771225576
Epoch : 102 -- m : 5.569815016722218 -- b : 23.25202963299507 -- cost : 617.9795289312884
Epoch : 103 -- m : 5.551918838121555 -- b : 23.439417065830153 -- cost : 614.4415791936567
Epoch : 104 -- m : 5.534078039306329 -- b : 23.62622462761815 -- cost : 610.9254919717391
Epoch : 105 -- m : 5.516292448903607 -- b : 23.812454112771988 -- cost : 607.4311321676322
Epoch : 106 -- m : 5.4985618960707665 -- b : 23.998107310151774 -- cost : 603.9583655182603
Epoch : 107 -- m : 5.480886210493862 -- b : 24.183186003081982 -- cost : 600.507058590217
Epoch : 108 -- m : 5.463265222385984 -- b : 24.367691969368583 -- cost : 597.0770787746385
Epoch : 109 -- m : 5.445698762485629 -- b : 24.551626981316115 -- cost : 593.6682942821085
Epoch : 110 -- m : 5.428186662055072 -- b : 24.734992805744724 -- cost : 590.280574137594
Epoch : 111 -- m : 5.410728752878752 -- b : 24.91779120400712 -- cost : 586.9137881754133
Epoch : 112 -- m : 5.393324867261645 -- b : 25.100023932005495 -- cost : 583.5678070342346
Epoch : 113 -- m : 5.375974838027668 -- b : 25.281692740208406 -- cost : 580.2425021521052
Epoch : 114 -- m : 5.358678498518057 -- b : 25.462799373667572 -- cost : 576.9377457615125
Epoch : 115 -- m : 5.341435682589779 -- b : 25.643345572034647 -- cost : 573.6534108844743
Epoch : 116 -- m : 5.324246224613931 -- b : 25.823333069577927 -- cost : 570.3893713276595
Epoch : 117 -- m : 5.307109959474146 -- b : 26.00276359519901 -- cost : 567.1455016775408
Epoch : 118 -- m : 5.290026722565013 -- b : 26.181638872449398 -- cost : 563.9216772955749
Epoch : 119 -- m : 5.272996349790493 -- b : 26.359960619547056 -- cost : 560.7177743134132
Epoch : 120 -- m : 5.2560186775623405 -- b : 26.537730549392926 -- cost : 557.5336696281436
Epoch : 121 -- m : 5.239093542798536 -- b : 26.714950369587363 -- cost : 554.3692408975596
Epoch : 122 -- m : 5.22222078292172 -- b : 26.891621782446553 -- cost : 551.2243665354604
Epoch : 123 -- m : 5.205400235857625 -- b : 27.067746485018855 -- cost : 548.0989257069782
Epoch : 124 -- m : 5.188631740033525 -- b : 27.24332616910111 -- cost : 544.9927983239357
Epoch : 125 -- m : 5.171915134376681 -- b : 27.418362521254885 -- cost : 541.905865040233
Epoch : 126 -- m : 5.155250258312795 -- b : 27.592857222822676 -- cost : 538.8380072472605
Epoch : 127 -- m : 5.1386369517644646 -- b : 27.766811949944064 -- cost : 535.7891070693425
Epoch : 128 -- m : 5.12207505514965 -- b : 27.940228373571802 -- cost : 532.759047359208
Epoch : 129 -- m : 5.105564409380137 -- b : 28.113108159487883 -- cost : 529.7477116934894
Epoch : 130 -- m : 5.08910485586001 -- b : 28.285452968319525 -- cost : 526.754984368249
Epoch : 131 -- m : 5.0726962364841315 -- b : 28.457264455555134 -- cost : 523.780750394534
Epoch : 132 -- m : 5.056338393636619 -- b : 28.628544271560195 -- cost : 520.8248954939576
Epoch : 133 -- m : 5.040031170189332 -- b : 28.79929406159314 -- cost : 517.8873060943085
Epoch : 134 -- m : 5.023774409500365 -- b : 28.96951546582114 -- cost : 514.9678693251869
Epoch : 135 -- m : 5.007567955412541 -- b : 29.139210119335857 -- cost : 512.0664730136681
Epoch : 136 -- m : 4.991411652251912 -- b : 29.308379652169165 -- cost : 509.1830056799918
Epoch : 137 -- m : 4.975305344826264 -- b : 29.477025689308796 -- cost : 506.3173565332795
Epoch : 138 -- m : 4.959248878423626 -- b : 29.64514985071395 -- cost : 503.4694154672775
Epoch : 139 -- m : 4.9432420988107815 -- b : 29.81275375133086 -- cost : 500.6390730561251
Epoch : 140 -- m : 4.927284852231791 -- b : 29.9798390011083 -- cost : 497.8262205501524
Epoch : 141 -- m : 4.9113769854065135 -- b : 30.146407205013055 -- cost : 495.0307498716997
Epoch : 142 -- m : 4.895518345529134 -- b : 30.312459963045335 -- cost : 492.252553610966
Epoch : 143 -- m : 4.879708780266695 -- b : 30.47799887025414 -- cost : 489.4915250218818
Epoch : 144 -- m : 4.863948137757633 -- b : 30.643025516752587 -- cost : 486.7475580180075
Epoch : 145 -- m : 4.848236266610321 -- b : 30.807541487733186 -- cost : 484.02054716845726
Epoch : 146 -- m : 4.832573015901617 -- b : 30.97154836348306 -- cost : 481.31038769384793
Epoch : 147 -- m : 4.816958235175408 -- b : 31.135047719399125 -- cost : 478.6169754622739
Epoch : 148 -- m : 4.801391774441166 -- b : 31.298041126003234 -- cost : 475.9402069853048
Epoch : 149 -- m : 4.785873484172515 -- b : 31.460530148957247 -- cost : 473.27997941401037
Epoch : 150 -- m : 4.770403215305785 -- b : 31.622516349078087 -- cost : 470.6361905350079
Epoch : 151 -- m : 4.754980819238583 -- b : 31.784001282352712 -- cost : 468.0087387665353
Epoch : 152 -- m : 4.73960614782837 -- b : 31.94498649995308 -- cost : 465.3975231545479
Epoch : 153 -- m : 4.724279053391032 -- b : 32.10547354825105 -- cost : 462.8024433688397
Epoch : 154 -- m : 4.708999388699466 -- b : 32.26546396883321 -- cost : 460.22339969918806
Epoch : 155 -- m : 4.693767006982162 -- b : 32.42495929851572 -- cost : 457.66029305152296
Epoch : 156 -- m : 4.678581761921795 -- b : 32.58396106935904 -- cost : 455.1130249441193
Epoch : 157 -- m : 4.663443507653821 -- b : 32.74247080868268 -- cost : 452.5814975038128
Epoch : 158 -- m : 4.6483520987650735 -- b : 32.900490039079855 -- cost : 450.0656134622399
Epoch : 159 -- m : 4.633307390292367 -- b : 33.05802027843209 -- cost : 447.5652761521002
Epoch : 160 -- m : 4.618309237721106 -- b : 33.21506303992384 -- cost : 445.08038950344155
Epoch : 161 -- m : 4.603357496983894 -- b : 33.371619832057 -- cost : 442.6108580399704
Epoch : 162 -- m : 4.588452024459154 -- b : 33.527692158665396 -- cost : 440.1565868753817
Epoch : 163 -- m : 4.573592676969747 -- b : 33.68328151892924 -- cost : 437.71748170971404
Epoch : 164 -- m : 4.558779311781591 -- b : 33.838389407389535 -- cost : 435.29344882572576
Epoch : 165 -- m : 4.544011786602302 -- b : 33.9930173139624 -- cost : 432.8843950852948
Epoch : 166 -- m : 4.529289959579814 -- b : 34.14716672395341 -- cost : 430.49022792583946
Epoch : 167 -- m : 4.514613689301029 -- b : 34.30083911807188 -- cost : 428.1108553567623
Epoch : 168 -- m : 4.499982834790447 -- b : 34.454035972445034 -- cost : 425.7461859559151
Epoch : 169 -- m : 4.485397255508818 -- b : 34.60675875863223 -- cost : 423.3961288660867
Epoch : 170 -- m : 4.470856811351795 -- b : 34.75900894363909 -- cost : 421.0605937915119
Epoch : 171 -- m : 4.456361362648579 -- b : 34.910787989931556 -- cost : 418.73949099440165
Epoch : 172 -- m : 4.441910770160587 -- b : 35.062097355449986 -- cost : 416.43273129149566
Epoch : 173 -- m : 4.427504895080109 -- b : 35.21293849362313 -- cost : 414.14022605063514
Epoch : 174 -- m : 4.413143599028974 -- b : 35.36331285338209 -- cost : 411.86188718735804
Epoch : 175 -- m : 4.398826744057225 -- b : 35.51322187917426 -- cost : 409.59762716151346
Epoch : 176 -- m : 4.384554192641794 -- b : 35.66266701097718 -- cost : 407.3473589738994
Epoch : 177 -- m : 4.370325807685171 -- b : 35.81164968431238 -- cost : 405.1109961629192
Epoch : 178 -- m : 4.356141452514102 -- b : 35.96017133025915 -- cost : 402.8884528012596
Epoch : 179 -- m : 4.342000990878264 -- b : 36.10823337546831 -- cost : 400.6796434925894
Epoch : 180 -- m : 4.327904286948965 -- b : 36.25583724217591 -- cost : 398.48448336827784
Epoch : 181 -- m : 4.3138512053178335 -- b : 36.40298434821687 -- cost : 396.30288808413417
Epoch : 182 -- m : 4.299841610995519 -- b : 36.54967610703862 -- cost : 394.1347738171671
Epoch : 183 -- m : 4.285875369410397 -- b : 36.69591392771469 -- cost : 391.98005726236295
Epoch : 184 -- m : 4.271952346407276 -- b : 36.841699214958204 -- cost : 389.8386556294862
Epoch : 185 -- m : 4.258072408246106 -- b : 36.9870333691354 -- cost : 387.7104866398977
Epoch : 186 -- m : 4.244235421600697 -- b : 37.1319177862791 -- cost : 385.5954685233933
Epoch : 187 -- m : 4.230441253557439 -- b : 37.27635385810206 -- cost : 383.4935200150624
Epoch : 188 -- m : 4.216689771614021 -- b : 37.42034297201042 -- cost : 381.4045603521652
Epoch : 189 -- m : 4.202980843678163 -- b : 37.56388651111694 -- cost : 379.3285092710297
Epoch : 190 -- m : 4.189314338066344 -- b : 37.70698585425438 -- cost : 377.2652870039675
Epoch : 191 -- m : 4.175690123502538 -- b : 37.84964237598866 -- cost : 375.21481427620944
Epoch : 192 -- m : 4.162108069116954 -- b : 37.99185744663212 -- cost : 373.1770123028592
Epoch : 193 -- m : 4.148568044444776 -- b : 38.133632432256654 -- cost : 371.15180278586627
Epoch : 194 -- m : 4.135069919424914 -- b : 38.27496869470685 -- cost : 369.1391079110174
Epoch : 195 -- m : 4.121613564398753 -- b : 38.415867591613065 -- cost : 367.1388503449469
Epoch : 196 -- m : 4.108198850108903 -- b : 38.556330476404455 -- cost : 365.1509532321656
Epoch : 197 -- m : 4.094825647697966 -- b : 38.696358698321994 -- cost : 363.17534019210706
Epoch : 198 -- m : 4.081493828707291 -- b : 38.83595360243142 -- cost : 361.21193531619343
Epoch : 199 -- m : 4.068203265075744 -- b : 38.97511652963615 -- cost : 359.26066316491904
Epoch : 200 -- m : 4.0549538291384755 -- b : 39.1138488166902 -- cost : 357.32144876495073
Epoch : 201 -- m : 4.041745393625696 -- b : 39.25215179621097 -- cost : 355.39421760624845
Epoch : 202 -- m : 4.028577831661454 -- b : 39.39002679669207 -- cost : 353.47889563920154
Epoch : 203 -- m : 4.015451016762413 -- b : 39.5274751425161 -- cost : 351.5754092717838
Epoch : 204 -- m : 4.002364822836642 -- b : 39.66449815396735 -- cost : 349.68368536672574
Epoch : 205 -- m : 3.989319124182403 -- b : 39.80109714724448 -- cost : 347.8036512387051
Epoch : 206 -- m : 3.9763137954869383 -- b : 39.937273434473155 -- cost : 345.9352346515527
Epoch : 207 -- m : 3.9633487118252746 -- b : 40.07302832371869 -- cost : 344.0783638154786
Epoch : 208 -- m : 3.9504237486590177 -- b : 40.20836311899857 -- cost : 342.23296738431225
Epoch : 209 -- m : 3.937538781835159 -- b : 40.343279120295 -- cost : 340.3989744527623
Epoch : 210 -- m : 3.9246936875848806 -- b : 40.477777623567384 -- cost : 338.5763145536914
Epoch : 211 -- m : 3.9118883425223685 -- b : 40.61185992076477 -- cost : 336.7649176554093
Epoch : 212 -- m : 3.899122623643626 -- b : 40.74552729983828 -- cost : 334.9647141589815
Epoch : 213 -- m : 3.8863964083252927 -- b : 40.878781044753445 -- cost : 333.1756348955555
Epoch : 214 -- m : 3.8737095743234673 -- b : 41.01162243550258 -- cost : 331.39761112370263
Epoch : 215 -- m : 3.8610619997725317 -- b : 41.14405274811705 -- cost : 329.6305745267774
Epoch : 216 -- m : 3.8484535631839827 -- b : 41.27607325467954 -- cost : 327.8744572102924
Epoch : 217 -- m : 3.8358841434452615 -- b : 41.407685223336266 -- cost : 326.1291916993091
Epoch : 218 -- m : 3.8233536198185947 -- b : 41.53888991830917 -- cost : 324.39471093584615
Epoch : 219 -- m : 3.810861871939831 -- b : 41.669688599908035 -- cost : 322.670948276302
Epoch : 220 -- m : 3.7984087798172874 -- b : 41.80008252454264 -- cost : 320.95783748889477
Epoch : 221 -- m : 3.7859942238305955 -- b : 41.930072944734775 -- cost : 319.2553127511174

In [146]:
model1.run_epoch(x_train , y_train)

Epoch : 993 -- m : 0.15208949043612524 -- b : 79.97998820054468 -- cost : 47.72975076636046

In [147]:
y_test

array(68.2)

In [149]:
y_train

array([ 87.5,  77.4,  96.9, 100. ,  87.8,  79.2,  81.3,  90.4,  78.7,
        79.2,  92.1,  82.7,  82.7,  87.5,  87.9,  92.4,  82.7,  80. ,
        74.8,  87.3,  73.8,  78.8,  83.2,  58. ,  70.5,  83.8,  82.4,
        75.5,  82. ,  82.7, 100. ,  63.6,  87.2,  89.4,  79.6, 100. ,
        69.1,  83.3,  82.7,  82.7,  87.3,  72.5,  86.2,  81.3,  82.7,
        90.3, 100. ,  86.1,  80.2,  91.2,  91.1,  95.6,  97.8,  81.9,
        74.1,  82.7,  89.6,  84.4,  89.8,  78.7,  78.7,  84.2,  69.5,
       100. ,  82. ,  79.8,  78.8, 100. ,  82.7,  76. ,  80.7,  67.1,
        86.5,  86.1,  82.7,  69.5,  56.8,  77.1,  82.7,  82.7,  54.2,
        82.7,  65.5,  88.5,  71. ,  99.2,  83.5,  80.7,  82.7,  63.5,
        71.7,  83.3,  74.3,  86.9,  83.4,  86.2,  99.3,  95.6,  82.6,
        82.7,  82.4,  90.8,  85.8,  78.4,  84.8,  83.3,  72.9,  77.1,
        62.9,  84.7,  91.5,  87.6,  86.5,  69.7,  55.8,  98.6,  65.7,
        76.2,  65.1,  78. ,  77.7,  78.6,  91.9,  87.3,  79.1,  93.7,
        81.1,  77.6,  83.6,  82.7,  73.2,  89.4,  82. ,  71.3,  82.7,
        84.9,  99.3,  82.9,  80.9,  94.5,  89.6,  65. ,  82.2,  90.1,
        87.7,  99.4,  65.2])

In [ ]:
for