In [228]:
import numpy as np
import pandas as pd

In [229]:
lap = pd.read_csv(r"C:\Users\HP\Desktop\AI_project\week-04-libraries-descriptive-statistics\datasets\laptops_test.csv")

In [230]:
lap['Manufacturer'].unique()

<StringArray>
[     'HP',    'Asus',    'Dell', 'Toshiba',  'Lenovo', 'Fujitsu',    'Acer',
     'MSI',    'Vero',   'Apple',   'Razer', 'Samsung']
Length: 12, dtype: str

In [231]:
lap

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,15-bs053od (i7-7500U/6GB/1TB/W10),Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Rog GL753VE-DS74,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,Inspiron 7579,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Portege Z30-C-1CV,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,IdeaPad 320-15ABR,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,"14.0""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,"13.3""",IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,IdeaPad 100S-14IBR,Notebook,"14.0""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,"15.6""",1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,"15.6""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [232]:
lap.drop("Model Name" , axis=1,inplace=True)

In [233]:
lap

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,2 in 1 Convertible,"14.0""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,2 in 1 Convertible,"13.3""",IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,Notebook,"14.0""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,Notebook,"15.6""",1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,Notebook,"15.6""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [234]:
lap['Category'].unique()

<StringArray>
[          'Notebook',             'Gaming', '2 in 1 Convertible',
            'Netbook',          'Ultrabook',        'Workstation']
Length: 6, dtype: str

In [235]:
lap['Category'] =='Notebook'

0       True
1      False
2      False
3       True
4       True
       ...
320    False
321    False
322     True
323     True
324     True
Name: Category, Length: 325, dtype: bool

In [236]:
lap[lap['Category'] =='Netbook'].count()

Manufacturer                8
Category                    8
Screen Size                 8
Screen                      8
CPU                         8
RAM                         8
 Storage                    8
GPU                         8
Operating System            8
Operating System Version    6
Weight                      8
Price                       8
dtype: int64

In [237]:

lap['Category'].apply(lambda s: s.lower())

0                notebook
1                  gaming
2      2 in 1 convertible
3                notebook
4                notebook
              ...
320    2 in 1 convertible
321    2 in 1 convertible
322              notebook
323              notebook
324              notebook
Name: Category, Length: 325, dtype: str

In [238]:
lap["Category"]

0                Notebook
1                  Gaming
2      2 in 1 Convertible
3                Notebook
4                Notebook
              ...
320    2 in 1 Convertible
321    2 in 1 Convertible
322              Notebook
323              Notebook
324              Notebook
Name: Category, Length: 325, dtype: str

In [239]:
lap['Screen Size']

0      15.6"
1      17.3"
2      15.6"
3      13.3"
4      15.6"
       ...
320    14.0"
321    13.3"
322    14.0"
323    15.6"
324    15.6"
Name: Screen Size, Length: 325, dtype: str

In [240]:
lap['Screen Size'] = lap['Screen Size'].apply(lambda s : s.replace('"' , ''))

In [241]:
lap

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [242]:
lap.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    str
 1   Category                  325 non-null    str
 2   Screen Size               325 non-null    str
 3   Screen                    325 non-null    str
 4   CPU                       325 non-null    str
 5   RAM                       325 non-null    str
 6    Storage                  325 non-null    str
 7   GPU                       325 non-null    str
 8   Operating System          325 non-null    str
 9   Operating System Version  291 non-null    str
 10  Weight                    325 non-null    str
 11  Price                     325 non-null    float64
dtypes: float64(1), str(11)
memory usage: 30.6 KB

In [243]:
lap.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [244]:
lap['Screen Size'] = lap['Screen Size'].astype(float)
lap

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [245]:
lap.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    str
 1   Category                  325 non-null    str
 2   Screen Size               325 non-null    float64
 3   Screen                    325 non-null    str
 4   CPU                       325 non-null    str
 5   RAM                       325 non-null    str
 6    Storage                  325 non-null    str
 7   GPU                       325 non-null    str
 8   Operating System          325 non-null    str
 9   Operating System Version  291 non-null    str
 10  Weight                    325 non-null    str
 11  Price                     325 non-null    float64
dtypes: float64(2), str(10)
memory usage: 30.6 KB

In [246]:
lap["Screen"].apply(lambda s : s.split()[-1])

0       1366x768
1      1920x1080
2      1920x1080
3      1920x1080
4      1920x1080
         ...
320    1920x1080
321    3200x1800
322     1366x768
323     1366x768
324     1366x768
Name: Screen, Length: 325, dtype: str

In [247]:
lap

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [248]:
lap["CPU"].unique()

<StringArray>
[          'Intel Core i7 7500U 2.7GHz',
          'Intel Core i7 7700HQ 2.8GHz',
           'Intel Core i5 6200U 2.3GHz',
          'AMD A12-Series 9720P 3.6GHz',
           'Intel Core i5 7200U 2.5GHz',
             'Intel Core M 6Y75 1.2GHz',
             'Intel Core i3 6006U 2GHz',
 'Intel Celeron Dual Core N3350 1.1GHz',
 'Intel Pentium Quad Core N4200 1.1GHz',
           'Intel Core i3 7100U 2.4GHz',
           'Intel Core i5 6300U 2.4GHz',
           'Intel Core i7 6600U 2.6GHz',
          'Intel Core i5 7300HQ 2.5GHz',
           'Intel Core i7 6500U 2.5GHz',
          'Intel Core i7 6820HQ 2.7GHz',
           'Intel Core i3 6100U 2.3GHz',
              'AMD A9-Series 9420 3GHz',
          'Intel Atom X5-Z8350 1.44GHz',
          'Intel Core i7 6820HK 2.7GHz',
          'Intel Core i7 6700HQ 2.6GHz',
 'Intel Celeron Dual Core N3060 1.6GHz',
           'Intel Core i5 7200U 2.7GHz',
            'AMD A8-Series 7410 2.2GHz',
                  'Intel Core M 1.1GHz',
          'Intel Core i5 6300HQ 2.3GHz',
          'Intel Atom x5-Z8550 1.44GHz',
 'Intel Pentium Dual Core 4405Y 1.5GHz',
 'Intel Pentium Quad Core N3700 1.6GHz',
           'Intel Core i5 8250U 1.6GHz',
 'Intel Pentium Quad Core N3710 1.6GHz',
 'Intel Celeron Dual Core 3205U 1.5GHz',
            'AMD A6-Series 9220 2.5GHz',
             'Intel Core M 6Y54 1.1GHz',
           'Intel Core i3 6006U 2.0GHz',
           'Intel Core i7 7560U 2.4GHz',
          'Intel Core i7 6500U 2.50GHz',
             'AMD E-Series 7110 1.8GHz',
         'AMD A6-Series A6-9220 2.5GHz',
           'Intel Core i7 8550U 1.8GHz',
 'Intel Celeron Dual Core N3050 1.6GHz',
   'Intel Celeron Dual Core N3350 2GHz',
        'Samsung Cortex A72&A53 2.0GHz',
             'AMD E-Series 9000 2.2GHz',
                  'Intel Core M 1.2GHz',
            'Intel Core i7 7Y75 1.3GHz',
          'AMD A12-Series 9720P 2.7GHz',
                 'Intel Core i5 1.6GHz',
            'Intel Core i5 7Y54 1.2GHz',
             'Intel Core M 6Y30 0.9GHz',
            'AMD A9-Series 9410 2.9GHz']
Length: 50, dtype: str

In [249]:
lap['CPU'].apply( lambda s : s.split())

0                 [Intel, Core, i7, 7500U, 2.7GHz]
1                [Intel, Core, i7, 7700HQ, 2.8GHz]
2                 [Intel, Core, i7, 7500U, 2.7GHz]
3                 [Intel, Core, i5, 6200U, 2.3GHz]
4                 [AMD, A12-Series, 9720P, 3.6GHz]
                          ...
320               [Intel, Core, i7, 6500U, 2.5GHz]
321               [Intel, Core, i7, 6500U, 2.5GHz]
322    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
323               [Intel, Core, i7, 6500U, 2.5GHz]
324    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
Name: CPU, Length: 325, dtype: object

In [250]:
lap['company'] = lap['CPU'].apply( lambda s : s.split()[0])

In [251]:
lap ['genaretion']= lap['CPU'].apply( lambda s : s.split()[-3])

In [252]:
lap.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,genaretion
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series

In [253]:
lap ['gigahards']= lap['CPU'].apply( lambda s : s.split()[-2])

In [254]:
lap.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,genaretion,gigahards
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P

In [255]:
lap.columns

Index(['Manufacturer', 'Category', 'Screen Size', 'Screen', 'CPU', 'RAM',
       ' Storage', 'GPU', 'Operating System', 'Operating System Version',
       'Weight', 'Price', 'company', 'genaretion', 'gigahards'],
      dtype='str')

In [256]:
lap['Manufacturer'].unique()

<StringArray>
[     'HP',    'Asus',    'Dell', 'Toshiba',  'Lenovo', 'Fujitsu',    'Acer',
     'MSI',    'Vero',   'Apple',   'Razer', 'Samsung']
Length: 12, dtype: str

In [257]:
lap.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,genaretion,gigahards
0,HP,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U
1,Asus,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ
2,Dell,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U
3,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U
4,Lenovo,Notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P

In [258]:
import numpy as np
import pandas as pd

In [259]:
df =pd.read_csv(r"C:\Users\HP\Desktop\AI_project\week-04-libraries-descriptive-statistics\datasets\students.csv")

In [260]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    str
 1   gender       184 non-null    str
 2   city         184 non-null    str
 3   program      184 non-null    str
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), str(4)
memory usage: 14.5 KB

In [261]:
df.shape

(184, 10)

In [262]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [263]:
df.describe()

,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
count,184.000000,179.000000,168.000000,174.000000,184.000000,184.000000
mean,4.777174,7.256983,82.155357,2.839655,65.119565,0.423913
std,2.285454,4.888808,10.498998,0.582331,11.508669,0.495525
min,1.000000,0.500000,54.200000,1.370000,32.100000,0.000000
25%,3.000000,3.650000,76.000000,2.460000,58.175000,0.000000
50%,5.000000,6.400000,82.700000,2.875000,65.700000,0.000000
75%,7.000000,8.850000,89.400000,3.257500,72.725000,1.000000
max,8.000000,30.000000,100.000000,4.000000,92.400000,1.000000

In [264]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [269]:
ndf =df.copy()
m = df['study_hours'].mean()
df['study_hours'] = df['study_hours'].fillna(m)

In [270]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     0
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [ ]:

df['attendance'] = df['attendance'].fillna(df['attendance'].mean())
df.isnull().sum()

In [275]:

df['prev_gpa'] = df['prev_gpa'].fillna(df['prev_gpa'].mean())
df.isnull().sum()

student_id     0
gender         0
city           0
program        0
semester       0
study_hours    0
attendance     0
prev_gpa       0
final_marks    0
scholarship    0
dtype: int64

In [276]:
ndf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [294]:
df.info()

<class 'pandas.DataFrame'>
Index: 154 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   154 non-null    str
 1   gender       154 non-null    str
 2   city         154 non-null    str
 3   program      154 non-null    str
 4   semester     154 non-null    int64
 5   study_hours  154 non-null    float64
 6   attendance   154 non-null    float64
 7   prev_gpa     154 non-null    float64
 8   final_marks  154 non-null    float64
 9   scholarship  154 non-null    int64
dtypes: float64(4), int64(2), str(4)
memory usage: 13.2 KB

In [ ]:
df =pd.read_csv(r"C:\Users\HP\Desktop\AI_project\week-04-libraries-descriptive-statistics\datasets\students.csv")

In [279]:
df.shape

(184, 10)

In [286]:

df =df.dropna( axis= 0 , subset =['study_hours'])
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [288]:
df.shape

(179, 10)

In [289]:

df =df.dropna( axis= 0 , subset =['attendance'])
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [292]:

df =df.dropna( axis= 0 , subset =['prev_gpa'])
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
5,S1104,Female,Karachi,BBA,4,7.6,79.2,2.46,55.4,0
6,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
7,S1074,Male,Peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [293]:
df.shape

(154, 10)

In [302]:
pd.DataFrame(df.groupby('gender'))

        0                                                  1
0  Female      student_id  gender      city program  seme...
1    Male      student_id gender       city program  seme...
2  female      student_id  gender       city program  sem...
3    male      student_id gender      city program  semes...

In [303]:
df.groupby('gender')['study_hours'].mean()

gender
Female    7.759091
Male      7.216667
female    3.350000
male      5.750000
Name: study_hours, dtype: float64

In [ ]:
df.grou