In [171]:
import pandas as pd
import numpy as np

In [172]:
l = [32,25,25,65,98]
s = pd.Series(l)

In [173]:
s

0    32
1    25
2    25
3    65
4    98
dtype: int64

In [174]:

s

0    32
1    25
2    25
3    65
4    98
dtype: int64

In [175]:
s[3]

np.int64(65)

In [176]:
s[6]

KeyError: 6

In [ ]:
data = {
    "name" : {"name " : "shakoor",'age ' : 20}
}

In [ ]:
name = pd.Series(data)

In [ ]:
name

          name
name   shakoor
age         20

In [ ]:
df = pd.read_csv("Titanic_Dataset.csv")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.to_string()

'     PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked\n0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S\n1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C\n2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S\n3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S\n4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S\n5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q\n6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S\n7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S\n8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S\n9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C\n10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S\n11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S\n12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S\n13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S\n14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S\n15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S\n16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q\n17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S\n18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S\n19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C\n20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S\n21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S\n22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q\n23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S\n24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S\n25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S\n26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C\n27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S\n28            29         1       3                                                       O\'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q\n29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S\n30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C\n31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C\n32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q\n33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S\n34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C\n35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S\n36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C\n37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S\n38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S\n39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C\n40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S\n41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S\n42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C\n43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C\n44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q\n45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S\n46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q\n47            48         1       3                                                           O\'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q\n48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C\n49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S\n50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S\n51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S\n52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C\n53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S\n54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C\n55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S\n56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S\n57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C\n58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S\n59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S\n60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C\n61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN\n62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S\n63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S\n64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C\n65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C\n66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S\n67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S\n68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S\n69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S\n70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S\n71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S\n72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S\n73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C\n74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S\n75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S\n76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S\n77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S\n78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S\n79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S\n80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S\n81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S\n82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q\n83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S\n84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S\n85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S\n86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S\n87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S\n88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S\n89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S\n90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S\n91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S\n92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S\n93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S\n94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S\n95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S\n96            97         0       1                                                           Goldschmidt, Mr. Ge

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.options.display.max_rows

60

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.loc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [ ]:
df.index = df['PassengerId']

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.loc[6]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 6, dtype: object

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Survived']

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
df['Survived'] == 1

PassengerId
1      False
2       True
3       True
4       True
5      False
       ...
887    False
888     True
889    False
890     True
891    False
Name: Survived, Length: 891, dtype: bool

In [ ]:
df[df['Survived']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
876,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
880,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df_sity = pd.read_csv(r"C:\Users\HP\Desktop\AI_project\week-04-libraries-descriptive-statistics\datasets\city_info.csv")

In [ ]:
df_sity

        city                     province campus_type
0   Peshawar           Khyber Pakhtunkhwa        Main
1     Lahore                       Punjab        Main
2    Karachi                        Sindh        Main
3  Islamabad  Islamabad Capital Territory   Satellite
4     Quetta                  Balochistan   Satellite
5     Multan                       Punjab   Satellite

In [ ]:
df_sity[df_sity["city"] == "Peshawar"]

       city            province campus_type
0  Peshawar  Khyber Pakhtunkhwa        Main

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df["Fare"].mean()

np.float64(32.204207968574636)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df[(df["Sex"] == 'female') & (df ["Age"] > 40)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
12,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
16,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
53,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
133,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
168,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S
178,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
195,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
196,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
255,255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,NaN,S
260,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,NaN,S
269,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
273,273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.0,0,1,250644,19.5000,NaN,S
276,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
277,277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.7500,NaN,S
300,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
338,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C
363,363,0,3,"Barbara, Mrs. (Catherine David)",female,45.0,0,1,2691,14.4542,NaN,C
367,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C
381,381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C
433,433,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.0,1,0,SC/AH 3085,26.0000,NaN,S
441,441,1,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.0,1,1,F.C.C. 13529,26.2500,NaN,S
459,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,NaN,S
484,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
497,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C
514,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4000,NaN,C
524,524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.0,0,1,111361,57.9792,B18,C
527,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5000,NaN,S
557,557,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0,1,0,11755,39.6000,A16,C
572,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S
592,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C
639,639,0,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,3101295,39.6875,NaN,S
679,679,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,CA 2144,46.9000,NaN,S
707,707,1,2,"Kelly, Mrs. Florence ""Fannie""",female,45.0,0,0,223596,13.5000,NaN,S
737,737,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S
755,755,1,2,"Herman, Mrs. Samuel (Jane Laver)",female,48.0,1,2,220845,65.0000,NaN,S
766,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S
773,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S
775,775,1,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S
780,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
797,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.0,0,0,17465,25.9292,D17,S
821,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
830,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
855,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S
857,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
866,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
872,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
880,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [ ]:
female_above = df[(df["Sex"] == 'female') & (df ["Age"] > 40)].shape

In [ ]:
female_above

(48, 12)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 122.8 KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
stu = pd.read_csv(r'C:\Users\HP\Desktop\AI_project\week-04-libraries-descriptive-statistics\datasets\students.csv')

In [ ]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [ ]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [ ]:
stu[stu["scholarship"] == 1]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1141,S1141,Male,Lahore,BSEE,5,3.2,92.1,3.35,54.4,1
S1168,S1168,Male,KARACHI,BSSE,3,7.8,82.7,2.79,67.7,1
S1045,S1045,Female,Multan,BSEE,7,3.2,NaN,3.31,42.7,1
S1129,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
S1166,S1166,Female,Multan,BSEE,7,7.4,80.0,3.21,64.0,1
...,...,...,...,...,...,...,...,...,...,...
S1136,S1136,Female,Lahore,BBA,5,5.9,68.8,2.93,64.8,1
S1042,S1042,Female,Karachi,BSSE,3,4.4,67.2,3.74,49.9,1
S1110,S1110,Male,Quetta,BBA,4,1.0,75.0,3.86,51.2,1
S1072,S1072,Female,Lahore,BSSE,4,4.8,70.5,2.88,65.1,1
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1

In [ ]:
stu[stu["attendance"] >= 75]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
S1023,S1023,Female,Peshawar,BBA,2,5.6,99.8,1.85,67.4,0
S1142,S1142,Female,Lahore,BSEE,8,4.6,99.8,2.99,70.3,0
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [ ]:
stu['city']

0        Quetta
1       Karachi
2        Lahore
3      PESHAWAR
4        Quetta
         ...
179    Peshawar
180    Peshawar
181      Lahore
182    Peshawar
183     Karachi
Name: city, Length: 184, dtype: str

In [ ]:
stu.iloc[6]

student_id        S1032
gender             Male
city           Peshawar
program             BBA
semester              2
study_hours         0.5
attendance         81.3
prev_gpa           2.17
final_marks        48.3
scholarship           0
Name: 6, dtype: object

In [ ]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [ ]:
st.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [ ]:
stu [ stu ['city'] == 'Peshawar']

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1032,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
S1074,S1074,Male,Peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
S1121,S1121,Female,Peshawar,BSCS,4,30.0,78.7,3.23,92.4,0
S1129,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
S1091,S1091,Female,Peshawar,BSEE,6,6.6,87.3,3.75,72.1,1
S1080,S1080,Female,Peshawar,BSEE,5,8.1,70.5,3.21,63.3,1
S1088,S1088,Male,Peshawar,BSCS,8,6.1,83.8,2.91,80.0,1
S1169,S1169,Female,Peshawar,BSCS,8,8.0,82.4,3.11,59.6,0
S1078,S1078,Male,Peshawar,BSSE,4,14.1,75.5,3.30,76.0,1
S1036,S1036,Male,Peshawar,BSSE,8,8.3,82.0,2.89,63.8,0
S1102,S1102,Male,Peshawar,BSEE,6,5.0,79.6,3.43,62.6,1
S1128,S1128,Male,Peshawar,BBA,3,6.1,100.0,2.57,85.0,0
S1011,S1011,Female,Peshawar,BSCS,4,15.0,87.3,2.12,71.2,0
S1109,S1109,Female,Peshawar,BBA,1,2.3,100.0,2.88,45.1,0
S1037,S1037,Male,Peshawar,BSCS,5,8.3,86.1,2.14,65.9,0
S1113,S1113,Male,Peshawar,BSCS,6,8.4,80.2,2.95,68.7,0
S1028,S1028,Male,Peshawar,BSCS,8,6.3,91.2,2.48,62.3,0
S1049,S1049,Male,Peshawar,BSEE,6,2.7,78.7,2.39,55.5,1
S1046,S1046,Male,Peshawar,BSCS,7,0.5,69.5,3.96,57.4,0
S1171,S1171,Male,Peshawar,BSSE,4,1.2,82.0,3.55,52.9,0
S1156,S1156,Male,Peshawar,BSCS,1,5.0,79.8,2.76,65.6,0
S1085,S1085,Male,Peshawar,BSSE,1,6.4,100.0,2.95,80.6,0
S1062,S1062,Male,Peshawar,BSCS,8,NaN,NaN,3.39,63.0,1
S1026,S1026,Male,Peshawar,BSSE,2,7.2,80.7,2.85,77.5,1
S1160,S1160,Male,Peshawar,BSEE,5,5.3,NaN,1.37,53.6,0
S1007,S1007,Female,Peshawar,BSSE,8,15.8,69.5,2.96,84.8,0
S1154,S1154,Male,Peshawar,BSCS,6,15.6,NaN,3.24,75.6,1
S1086,S1086,Female,Peshawar,BSEE,1,2.5,65.5,3.08,62.5,0
S1106,S1106,Male,Peshawar,BBA,2,4.7,71.0,2.50,56.1,0
S1111,S1111,Male,Peshawar,BBA,3,6.5,99.2,NaN,77.4,1
S1077,S1077,Female,Peshawar,BBA,7,9.8,71.7,3.19,70.9,0
S1090,S1090,Male,Peshawar,BSCS,6,6.4,83.4,3.24,73.5,1
S1132,S1132,Female,Peshawar,BSSE,4,7.7,95.6,3.56,82.4,0
S1059,S1059,male,Peshawar,BSEE,5,0.6,82.4,2.42,45.5,0
S1015,S1015,Male,Peshawar,BSCS,1,5.1,90.8,2.07,56.8,0
S1014,S1014,Male,Peshawar,BSCS,3,0.9,84.8,2.76,59.8,0
S1009,S1009,Male,Peshawar,BSEE,2,3.9,77.1,3.71,68.4,1
S1012,S1012,Female,Peshawar,BSCS,7,0.5,87.6,2.25,48.5,0
S1058,S1058,Male,Peshawar,BSCS,6,5.9,55.8,2.51,58.5,0
S1138,S1138,Female,Peshawar,BSCS,7,2.5,65.7,2.17,38.1,0
S1018,S1018,Female,Peshawar,BSCS,1,10.2,65.1,NaN,71.4,1
S1050,S1050,Male,Peshawar,BSSE,4,12.6,78.0,3.72,78.0,0
S1073,S1073,Male,Peshawar,BSSE,8,6.4,93.7,3.61,71.2,1
S1101,S1101,Female,Peshawar,BSCS,8,5.8,81.1,2.04,62.4,0
S1100,S1100,Female,Peshawar,BBA,5,14.4,99.3,2.81,86.0,0
S1083,S1083,Male,Peshawar,BSCS,5,18.2,79.6,2.28,90.4,0
S1087,S1087,Male,Peshawar,BBA,4,6.6,99.7,2.46,62.8,0
S1044,S1044,Female,Peshawar,BSEE,7,11.9,76.0,2.76,70.8,0
S1167,S1167,Female,Peshawar,BSEE,4,8.9,97.5,3.91,72.7,1
S1089,S1089,Male,Peshawar,BBA,8,18.9,86.9,3.21,91.8,0
S1023,S1023,Female,Peshawar,BBA,2,5.6,99.8,1.85,67.4,0
S1092,S1092,Male,Peshawar,BSSE,4,2.5,NaN,3.60,60.9,0
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0

In [ ]:
pesh =stu [ stu ['city'] == 'Peshawar']
pesh.info()

<class 'pandas.DataFrame'>
Index: 55 entries, S1032 to S1025
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   55 non-null     str
 1   gender       55 non-null     str
 2   city         55 non-null     str
 3   program      55 non-null     str
 4   semester     55 non-null     int64
 5   study_hours  54 non-null     float64
 6   attendance   51 non-null     float64
 7   prev_gpa     53 non-null     float64
 8   final_marks  55 non-null     float64
 9   scholarship  55 non-null     int64
dtypes: float64(4), int64(2), str(4)
memory usage: 4.7+ KB

In [ ]:
pesh.describe()

        semester  study_hours  attendance   prev_gpa  final_marks  scholarship
count  55.000000    54.000000   51.000000  53.000000    55.000000    55.000000
mean    4.781818     7.314815   82.905882   2.898868    67.081818     0.309091
std     2.322920     5.527680   10.992678   0.601740    12.108171     0.466378
min     1.000000     0.500000   55.800000   1.370000    38.100000     0.000000
25%     3.000000     3.675000   76.550000   2.420000    59.700000     0.000000
50%     5.000000     6.350000   82.000000   2.910000    65.900000     0.000000
75%     7.000000     8.375000   90.600000   3.300000    74.550000     1.000000
max     8.000000    30.000000  100.000000   3.960000    92.400000     1.000000

In [ ]:
male =stu [ (stu ['city'] == 'Peshawar') & ( stu['gender'] == "Male")]
male

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1032,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
S1074,S1074,Male,Peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
S1088,S1088,Male,Peshawar,BSCS,8,6.1,83.8,2.91,80.0,1
S1078,S1078,Male,Peshawar,BSSE,4,14.1,75.5,3.30,76.0,1
S1036,S1036,Male,Peshawar,BSSE,8,8.3,82.0,2.89,63.8,0
S1102,S1102,Male,Peshawar,BSEE,6,5.0,79.6,3.43,62.6,1
S1128,S1128,Male,Peshawar,BBA,3,6.1,100.0,2.57,85.0,0
S1037,S1037,Male,Peshawar,BSCS,5,8.3,86.1,2.14,65.9,0
S1113,S1113,Male,Peshawar,BSCS,6,8.4,80.2,2.95,68.7,0
S1028,S1028,Male,Peshawar,BSCS,8,6.3,91.2,2.48,62.3,0
S1049,S1049,Male,Peshawar,BSEE,6,2.7,78.7,2.39,55.5,1
S1046,S1046,Male,Peshawar,BSCS,7,0.5,69.5,3.96,57.4,0
S1171,S1171,Male,Peshawar,BSSE,4,1.2,82.0,3.55,52.9,0
S1156,S1156,Male,Peshawar,BSCS,1,5.0,79.8,2.76,65.6,0
S1085,S1085,Male,Peshawar,BSSE,1,6.4,100.0,2.95,80.6,0
S1062,S1062,Male,Peshawar,BSCS,8,NaN,NaN,3.39,63.0,1
S1026,S1026,Male,Peshawar,BSSE,2,7.2,80.7,2.85,77.5,1
S1160,S1160,Male,Peshawar,BSEE,5,5.3,NaN,1.37,53.6,0
S1154,S1154,Male,Peshawar,BSCS,6,15.6,NaN,3.24,75.6,1
S1106,S1106,Male,Peshawar,BBA,2,4.7,71.0,2.50,56.1,0
S1111,S1111,Male,Peshawar,BBA,3,6.5,99.2,NaN,77.4,1
S1090,S1090,Male,Peshawar,BSCS,6,6.4,83.4,3.24,73.5,1
S1015,S1015,Male,Peshawar,BSCS,1,5.1,90.8,2.07,56.8,0
S1014,S1014,Male,Peshawar,BSCS,3,0.9,84.8,2.76,59.8,0
S1009,S1009,Male,Peshawar,BSEE,2,3.9,77.1,3.71,68.4,1
S1058,S1058,Male,Peshawar,BSCS,6,5.9,55.8,2.51,58.5,0
S1050,S1050,Male,Peshawar,BSSE,4,12.6,78.0,3.72,78.0,0
S1073,S1073,Male,Peshawar,BSSE,8,6.4,93.7,3.61,71.2,1
S1083,S1083,Male,Peshawar,BSCS,5,18.2,79.6,2.28,90.4,0
S1087,S1087,Male,Peshawar,BBA,4,6.6,99.7,2.46,62.8,0
S1089,S1089,Male,Peshawar,BBA,8,18.9,86.9,3.21,91.8,0
S1092,S1092,Male,Peshawar,BSSE,4,2.5,NaN,3.60,60.9,0
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0

In [ ]:
lahore =stu [ (stu ['city'] == 'Lahore') ]
lahore

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
S1141,S1141,Male,Lahore,BSEE,5,3.2,92.1,3.35,54.4,1
S1174,S1174,Male,Lahore,BSCS,6,NaN,58.0,2.89,60.4,0
S1051,S1051,Male,Lahore,BSSE,6,3.0,89.4,2.32,69.0,0
S1130,S1130,Male,Lahore,BSSE,5,1.9,NaN,3.10,76.6,0
S1040,S1040,Male,Lahore,BSCS,1,4.5,91.1,3.24,76.1,1
S1095,S1095,Female,Lahore,BSCS,3,1.1,95.6,NaN,70.4,1
S1126,S1126,Male,Lahore,BBA,5,8.0,74.1,2.56,70.8,0
S1125,S1125,Male,Lahore,BBA,8,7.7,84.2,3.11,65.2,1
S1082,S1082,Female,Lahore,BSSE,7,2.1,67.1,2.60,47.0,0
S1041,S1041,Female,Lahore,BSEE,1,10.8,86.5,2.82,78.0,1
S1003,S1003,Female,Lahore,BSCS,5,7.5,80.7,3.43,60.8,1
S1039,S1039,Female,Lahore,BBA,4,14.1,NaN,3.10,83.0,0
S1096,S1096,Male,Lahore,BSEE,3,12.2,74.3,3.47,73.5,1
S1105,S1105,Female,Lahore,BSSE,3,3.9,62.9,3.07,42.2,1
S1107,S1107,Male,Lahore,BSEE,5,7.7,84.7,2.55,64.0,0
S1134,S1134,Female,Lahore,BSSE,1,1.0,NaN,1.79,46.5,0
S1133,S1133,Male,Lahore,BSCS,7,10.3,89.4,1.71,59.5,0
S1178,S1178,Female,Lahore,BSCS,5,6.2,87.7,3.06,52.3,1
S1056,S1056,Male,Lahore,BSCS,6,1.5,56.7,2.54,32.1,1
S1069,S1069,Male,Lahore,BSSE,7,2.7,75.3,1.66,46.8,0
S1019,S1019,Female,Lahore,BSSE,4,7.2,86.0,3.89,68.0,1
S1006,S1006,Female,Lahore,BSSE,7,7.5,70.0,3.28,65.7,1
S1135,S1135,Male,Lahore,BBA,1,6.3,88.2,3.34,72.5,1
S1068,S1068,Male,Lahore,BSCS,6,12.2,93.8,1.90,74.4,1
S1136,S1136,Female,Lahore,BBA,5,5.9,68.8,2.93,64.8,1
S1072,S1072,Female,Lahore,BSSE,4,4.8,70.5,2.88,65.1,1
S1142,S1142,Female,Lahore,BSEE,8,4.6,99.8,2.99,70.3,0
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0

In [ ]:
lahore.info()

<class 'pandas.DataFrame'>
Index: 29 entries, S1131 to S1067
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   29 non-null     str
 1   gender       29 non-null     str
 2   city         29 non-null     str
 3   program      29 non-null     str
 4   semester     29 non-null     int64
 5   study_hours  28 non-null     float64
 6   attendance   26 non-null     float64
 7   prev_gpa     27 non-null     float64
 8   final_marks  29 non-null     float64
 9   scholarship  29 non-null     int64
dtypes: float64(4), int64(2), str(4)
memory usage: 2.5+ KB

In [ ]:
lahore.describe()

        semester  study_hours  attendance   prev_gpa  final_marks  scholarship
count  29.000000    28.000000   26.000000  27.000000    29.000000    29.000000
mean    4.896552     5.832143   80.992308   2.804444    63.565517     0.551724
std     2.110261     3.668288   12.119370   0.580035    11.924832     0.506120
min     1.000000     1.000000   56.700000   1.660000    32.100000     0.000000
25%     4.000000     2.925000   71.400000   2.545000    59.500000     0.000000
50%     5.000000     5.350000   84.450000   2.930000    65.300000     1.000000
75%     7.000000     7.700000   89.400000   3.175000    70.800000     1.000000
max     8.000000    14.100000   99.800000   3.890000    83.000000     1.000000

In [ ]:
schl =stu [ (stu ['city'] == 'Peshawar') & ( stu['scholarship'] == 1)]

In [ ]:
schl

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
student_id,,,,,,,,,,
S1129,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
S1091,S1091,Female,Peshawar,BSEE,6,6.6,87.3,3.75,72.1,1
S1080,S1080,Female,Peshawar,BSEE,5,8.1,70.5,3.21,63.3,1
S1088,S1088,Male,Peshawar,BSCS,8,6.1,83.8,2.91,80.0,1
S1078,S1078,Male,Peshawar,BSSE,4,14.1,75.5,3.30,76.0,1
S1102,S1102,Male,Peshawar,BSEE,6,5.0,79.6,3.43,62.6,1
S1049,S1049,Male,Peshawar,BSEE,6,2.7,78.7,2.39,55.5,1
S1062,S1062,Male,Peshawar,BSCS,8,NaN,NaN,3.39,63.0,1
S1026,S1026,Male,Peshawar,BSSE,2,7.2,80.7,2.85,77.5,1
S1154,S1154,Male,Peshawar,BSCS,6,15.6,NaN,3.24,75.6,1
S1111,S1111,Male,Peshawar,BBA,3,6.5,99.2,NaN,77.4,1
S1090,S1090,Male,Peshawar,BSCS,6,6.4,83.4,3.24,73.5,1
S1009,S1009,Male,Peshawar,BSEE,2,3.9,77.1,3.71,68.4,1
S1018,S1018,Female,Peshawar,BSCS,1,10.2,65.1,NaN,71.4,1
S1073,S1073,Male,Peshawar,BSSE,8,6.4,93.7,3.61,71.2,1
S1167,S1167,Female,Peshawar,BSEE,4,8.9,97.5,3.91,72.7,1
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1

In [ ]:
stu['city'].unique()

<StringArray>
[   'Quetta',   'Karachi',    'Lahore',  'PESHAWAR',  'Peshawar',   'KARACHI',
    'Multan', 'Islamabad']
Length: 8, dtype: str

In [ ]:
attendacee ="fail"  if  stu['attendance'] < 75  else "pass"

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
attendance_short = stu ["attendance"] < 75

student_id
S1099    False
S1179    False
S1131    False
S1024    False
S1065    False
         ...
S1103     True
S1151     True
S1067    False
S1025    False
S1175    False
Name: attendance, Length: 184, dtype: bool

In [ ]:
stu['Attendance'] = attendance_short

In [ ]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance
student_id,,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False
...,...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False

In [182]:
 stu["Status"] = np.where(stu["attendance"] < 75 , "fail","pass")

In [183]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance,Status
student_id,,,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,pass
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,pass
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,pass
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False,pass
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,pass
...,...,...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,fail
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,fail
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,pass
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,pass
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,pass

In [184]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance,Status
student_id,,,,,,,,,,,,
S1099,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,pass
S1179,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,pass
S1131,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,pass
S1024,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False,pass
S1065,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,pass
...,...,...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,fail
S1151,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,fail
S1067,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,pass
S1025,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,pass
S1175,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,pass

In [191]:
def low (s):
    return s.lower()

In [196]:
 stu['city']=stu ['city '] =stu['city'].apply(low)

In [197]:
stu

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance,Status,city
student_id,,,,,,,,,,,,,
S1099,S1099,Female,quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,pass,quetta
S1179,S1179,Female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,pass,karachi
S1131,S1131,Female,lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,pass,lahore
S1024,S1024,Female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0,False,pass,peshawar
S1065,S1065,Male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,pass,quetta
...,...,...,...,...,...,...,...,...,...,...,...,...,...
S1103,S1103,Female,peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,fail,peshawar
S1151,S1151,Female,peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,fail,peshawar
S1067,S1067,Male,lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,pass,lahore
S1025,S1025,Male,peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,pass,peshawar
S1175,S1175,Male,karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,pass,karachi